/**
 * BrainSAIT Bilingual Clinical Lexicon (AR / EN / code-switch)
 * ---------------------------------------------------------------------------
 * A deterministic, explainable terminology dictionary that is the backbone of
 * the bilingual coding engine (`coding-engine.ts`) and the APR-DRG grouper
 * (`drg-grouper.ts`). Covers 70+ diagnoses across cardiovascular, respiratory,
 * endocrine, renal, GI, neuro, musculoskeletal, infectious, heme/onc, OB/GYN,
 * psychiatric, and pediatric medicine.
 *
 * Saudi clinical documentation is frequently *code-switched* — a physician
 * may write "sukari" (Arabic colloquial for diabetes, Latin-script), mix
 * Arabic medical terms into an English note ("ضغط دم مرتفع controlled with
 * medication"), or write a fully Arabic note. Existing coding engines assume
 * monolingual English input; this lexicon instead indexes every concept by
 * *all* of its English, Modern Standard Arabic, and Saudi-colloquial
 * (transliterated) forms so a single pass can recognize any mixture.
 *
 * DRG codes/weights are BrainSAIT's own calibration (not 3M-licensed APR-DRG/
 * EAPG values) and should be recalibrated against a certified grouper before
 * production reimbursement decisions.
 */
export interface SpecificityModifier {
  id: string;
  keywords_en: string[];
  keywords_ar: string[];
  prompt_en: string;
  prompt_ar: string;
  severity: 'info' | 'warning' | 'critical';
  /** Additional SOI points achievable if the gap is closed with a more specific code. */
  soi_gain: number;
}
export interface LexiconEntry {
  /** Canonical ICD-10-AM code suggested when this concept is matched with no further specificity. */
  code: string;
  desc_en: string;
  desc_ar: string;
  synonyms_en: string[];
  synonyms_ar: string[];
  /** Saudi colloquial / transliterated forms, e.g. "sukari" for diabetes. */
  synonyms_colloquial?: string[];
  base_confidence: number;
  /** Contribution to Severity of Illness when present as a secondary diagnosis (0-3). */
  soi_weight: number;
  /** Contribution to Risk of Mortality when present as a secondary diagnosis (0-3). */
  rom_weight: number;
  /** APR-DRG family this concept anchors when it is the principal diagnosis. */
  drg_family: string;
  /** Codes this entry supersedes when both match the same note (keeps the more specific code). */
  supersedes?: string[];
  specificity_modifiers?: SpecificityModifier[];
}
export const BILINGUAL_LEXICON: LexiconEntry[] = [
  {
    code: 'J18.9',
    desc_en: 'Pneumonia, unspecified organism',
    desc_ar: 'التهاب رئوي، غير محدد المسبب',
    synonyms_en: ['pneumonia', 'pneumonitis', 'lung infection'],
    synonyms_ar: ['التهاب رئوي', 'ذات الرئة', 'التهاب الرئة'],
    synonyms_colloquial: ['سعال شديد'],
    base_confidence: 0.85,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '194',
    specificity_modifiers: [
      {
        id: 'pneumonia_organism',
        keywords_en: ['bacterial', 'viral', 'streptococcus', 'klebsiella', 'organism', 'aspiration'],
        keywords_ar: ['بكتيري', 'فيروسي', 'المسبب', 'استنشاقي'],
        prompt_en: "Specify the causative organism for 'pneumonia' (e.g., bacterial, viral, aspiration) to support a more specific code.",
        prompt_ar: 'يرجى تحديد العامل المسبب لـ"الالتهاب الرئوي" (مثل بكتيري أو فيروسي أو استنشاقي) لدعم ترميز أكثر دقة.',
        severity: 'warning',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'I21.9',
    desc_en: 'Acute myocardial infarction, unspecified',
    desc_ar: 'احتشاء عضلة القلب الحاد، غير محدد',
    synonyms_en: ['myocardial infarction', 'heart attack', 'myocardial infarct', 'mi'],
    synonyms_ar: ['احتشاء عضلة القلب', 'نوبة قلبية', 'جلطة قلبية', 'جلطة في القلب'],
    base_confidence: 0.9,
    soi_weight: 3,
    rom_weight: 3,
    drg_family: '190',
    specificity_modifiers: [
      {
        id: 'mi_type',
        keywords_en: ['stemi', 'nstemi', 'st-elevation', 'non-st-elevation'],
        keywords_ar: ['احتشاء مرتفع', 'احتشاء غير مرتفع'],
        prompt_en: 'Specify the type of myocardial infarction (STEMI vs. NSTEMI) for a higher-specificity code.',
        prompt_ar: 'يرجى تحديد نوع احتشاء عضلة القلب (مع ارتفاع ST أو بدونه) لترميز أعلى دقة.',
        severity: 'critical',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'K37',
    desc_en: 'Unspecified appendicitis',
    desc_ar: 'التهاب الزائدة الدودية غير المحدد',
    synonyms_en: ['appendicitis', 'appendix pain', 'appendix inflammation'],
    synonyms_ar: ['التهاب الزائدة الدودية', 'الزائدة الدودية', 'التهاب الزايدة'],
    synonyms_colloquial: ['ألم الزائدة'],
    base_confidence: 0.9,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '261',
    specificity_modifiers: [
      {
        id: 'appendicitis_perforation',
        keywords_en: ['perforation', 'perforated', 'peritonitis', 'without perforation'],
        keywords_ar: ['انثقاب', 'مثقوبة', 'التهاب الصفاق', 'دون انثقاب'],
        prompt_en: 'Clarify if the appendicitis is with or without perforation/peritonitis.',
        prompt_ar: 'يرجى توضيح ما إذا كان التهاب الزائدة مصحوبًا بانثقاب أو التهاب الصفاق أم لا.',
        severity: 'warning',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'S82.90XA',
    desc_en: 'Unspecified fracture of lower leg, initial encounter',
    desc_ar: 'كسر غير محدد في أسفل الساق، الزيارة الأولى',
    synonyms_en: ['fracture', 'broken bone', 'broken leg'],
    synonyms_ar: ['كسر', 'كسر في العظم', 'كسر في الساق'],
    synonyms_colloquial: ['كسر'],
    base_confidence: 0.75,
    soi_weight: 1,
    rom_weight: 0,
    drg_family: '302',
    specificity_modifiers: [
      {
        id: 'fracture_laterality',
        keywords_en: ['left', 'right', 'bilateral'],
        keywords_ar: ['يسار', 'يمين', 'أيسر', 'أيمن', 'ثنائي', 'اليسرى', 'اليمنى', 'الأيسر', 'الأيمن'],
        prompt_en: "Specify laterality (left/right) for the diagnosed 'fracture' — required for a billable code.",
        prompt_ar: 'يرجى تحديد الجانب (يسار/يمين) للكسر المشخّص — مطلوب للحصول على رمز قابل للفوترة.',
        severity: 'critical',
        soi_gain: 0,
      },
    ],
  },
  {
    code: 'S82.202A',
    desc_en: 'Unspecified fracture of shaft of left tibia, initial encounter',
    desc_ar: 'كسر غير محدد في جسم عظمة الظنبوب اليسرى، الزيارة الأولى',
    synonyms_en: ['left leg fracture', 'left tibia fracture'],
    synonyms_ar: ['كسر الساق اليسرى', 'كسر الظنبوب الأيسر'],
    base_confidence: 0.88,
    soi_weight: 1,
    rom_weight: 0,
    drg_family: '302',
    supersedes: ['S82.90XA'],
  },
  {
    code: 'S82.201A',
    desc_en: 'Unspecified fracture of shaft of right tibia, initial encounter',
    desc_ar: 'كسر غير محدد في جسم عظمة الظنبوب اليمنى، الزيارة الأولى',
    synonyms_en: ['right leg fracture', 'right tibia fracture'],
    synonyms_ar: ['كسر الساق اليمنى', 'كسر الظنبوب الأيمن'],
    base_confidence: 0.88,
    soi_weight: 1,
    rom_weight: 0,
    drg_family: '302',
    supersedes: ['S82.90XA'],
  },
  {
    code: 'N39.0',
    desc_en: 'Urinary tract infection, site not specified',
    desc_ar: 'التهاب المسالك البولية، الموضع غير محدد',
    synonyms_en: ['uti', 'urinary tract infection'],
    synonyms_ar: ['التهاب المسالك البولية', 'التهاب البول'],
    base_confidence: 0.8,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '466',
    specificity_modifiers: [
      {
        id: 'uti_site',
        keywords_en: ['cystitis', 'pyelonephritis', 'urosepsis', 'catheter-associated', 'catheter'],
        keywords_ar: ['التهاب المثانة', 'التهاب الحويضة والكلية', 'إنتان بولي', 'قسطرة'],
        prompt_en: 'Specify the site (cystitis, pyelonephritis) or catheter association for the UTI.',
        prompt_ar: 'يرجى تحديد موضع التهاب المسالك البولية (التهاب المثانة أو الحويضة والكلية) أو علاقته بالقسطرة.',
        severity: 'warning',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'E11.9',
    desc_en: 'Type 2 diabetes mellitus without complications',
    desc_ar: 'داء السكري من النوع الثاني بدون مضاعفات',
    synonyms_en: ['diabetes', 'diabetic', 'type 2 diabetes', 'diabetes mellitus'],
    synonyms_ar: ['السكري', 'داء السكري', 'مرض السكر', 'سكر'],
    synonyms_colloquial: ['sukari'],
    base_confidence: 0.9,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '420',
    specificity_modifiers: [
      {
        id: 'diabetes_complication',
        keywords_en: ['neuropathy', 'nephropathy', 'retinopathy', 'ketoacidosis', 'with complication'],
        keywords_ar: ['اعتلال الأعصاب', 'اعتلال الكلى', 'اعتلال الشبكية', 'الحماض الكيتوني', 'مع مضاعفات'],
        prompt_en: 'Document any diabetic complication (neuropathy, nephropathy, retinopathy, ketoacidosis) if present — this materially changes SOI.',
        prompt_ar: 'يرجى توثيق أي مضاعفات لداء السكري (اعتلال الأعصاب/الكلى/الشبكية أو الحماض الكيتوني) إن وُجدت — يؤثر ذلك بشكل جوهري على درجة شدة المرض.',
        severity: 'warning',
        soi_gain: 2,
      },
    ],
  },
  {
    code: 'I10',
    desc_en: 'Essential (primary) hypertension',
    desc_ar: 'ارتفاع ضغط الدم الأساسي (الأولي)',
    synonyms_en: ['hypertension', 'high blood pressure'],
    synonyms_ar: ['ارتفاع ضغط الدم', 'ضغط الدم المرتفع', 'ضغط مرتفع', 'ضغط الدم'],
    synonyms_colloquial: ['ضغط دم مرتفع'],
    base_confidence: 0.99,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '201',
    specificity_modifiers: [
      {
        id: 'htn_crisis',
        keywords_en: ['crisis', 'emergency', 'urgency', 'malignant'],
        keywords_ar: ['أزمة', 'طارئ', 'خبيث'],
        prompt_en: "Clarify whether this represents a hypertensive crisis/emergency for a higher-acuity code.",
        prompt_ar: 'يرجى توضيح ما إذا كانت الحالة أزمة ارتفاع ضغط دم طارئة لترميز أعلى حدة.',
        severity: 'info',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'J44.9',
    desc_en: 'Chronic obstructive pulmonary disease, unspecified',
    desc_ar: 'مرض الانسداد الرئوي المزمن، غير محدد',
    synonyms_en: ['copd', 'chronic obstructive pulmonary disease', 'chronic bronchitis'],
    synonyms_ar: ['الانسداد الرئوي المزمن', 'مرض الانسداد الرئوي', 'التهاب الشعب الهوائية المزمن'],
    base_confidence: 0.87,
    soi_weight: 2,
    rom_weight: 1,
    drg_family: '140',
    specificity_modifiers: [
      {
        id: 'copd_exacerbation',
        keywords_en: ['exacerbation', 'acute exacerbation', 'decompensated'],
        keywords_ar: ['تفاقم', 'تفاقم حاد'],
        prompt_en: 'Specify if this is an acute exacerbation of COPD.',
        prompt_ar: 'يرجى تحديد ما إذا كانت الحالة تفاقمًا حادًا لمرض الانسداد الرئوي المزمن.',
        severity: 'warning',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'A41.9',
    desc_en: 'Sepsis, unspecified organism',
    desc_ar: 'تعفن الدم، غير محدد المسبب',
    synonyms_en: ['sepsis', 'septicemia', 'blood infection'],
    synonyms_ar: ['تعفن الدم', 'إنتان الدم', 'تسمم الدم'],
    base_confidence: 0.88,
    soi_weight: 3,
    rom_weight: 3,
    drg_family: '720',
    specificity_modifiers: [
      {
        id: 'sepsis_shock',
        keywords_en: ['septic shock', 'severe sepsis', 'organ dysfunction'],
        keywords_ar: ['صدمة إنتانية', 'إنتان شديد', 'قصور الأعضاء'],
        prompt_en: 'Document whether severe sepsis or septic shock is present — this is a major SOI/ROM driver.',
        prompt_ar: 'يرجى توثيق ما إذا كان هناك إنتان شديد أو صدمة إنتانية — فهذا عامل رئيسي في درجة الشدة وخطر الوفاة.',
        severity: 'critical',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'N18.9',
    desc_en: 'Chronic kidney disease, unspecified',
    desc_ar: 'الفشل الكلوي المزمن، غير محدد',
    synonyms_en: ['chronic kidney disease', 'ckd', 'chronic renal failure'],
    synonyms_ar: ['الفشل الكلوي المزمن', 'قصور كلوي مزمن', 'مرض الكلى المزمن'],
    base_confidence: 0.86,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '460',
    specificity_modifiers: [
      {
        id: 'ckd_stage',
        keywords_en: ['stage 1', 'stage 2', 'stage 3', 'stage 4', 'stage 5', 'esrd', 'dialysis'],
        keywords_ar: ['المرحلة الأولى', 'المرحلة الثانية', 'المرحلة الثالثة', 'المرحلة الرابعة', 'المرحلة الخامسة', 'غسيل كلوي'],
        prompt_en: 'Specify the CKD stage (1-5) or dialysis dependency for accurate severity capture.',
        prompt_ar: 'يرجى تحديد مرحلة الفشل الكلوي المزمن (1-5) أو الاعتماد على الغسيل الكلوي لتوثيق دقيق لدرجة الشدة.',
        severity: 'warning',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'J45.909',
    desc_en: 'Unspecified asthma, uncomplicated',
    desc_ar: 'الربو غير المحدد، بدون مضاعفات',
    synonyms_en: ['asthma', 'asthmatic', 'wheezing'],
    synonyms_ar: ['الربو', 'الربو الشعبي', 'أزيز'],
    base_confidence: 0.85,
    soi_weight: 1,
    rom_weight: 0,
    drg_family: '141',
  },
  {
    code: 'I63.9',
    desc_en: 'Cerebral infarction, unspecified',
    desc_ar: 'احتشاء دماغي، غير محدد',
    synonyms_en: ['stroke', 'cva', 'cerebral infarction', 'cerebrovascular accident'],
    synonyms_ar: ['سكتة دماغية', 'جلطة دماغية', 'احتشاء دماغي'],
    base_confidence: 0.9,
    soi_weight: 3,
    rom_weight: 3,
    drg_family: '045',
  },
  {
    code: 'I50.9',
    desc_en: 'Heart failure, unspecified',
    desc_ar: 'قصور القلب، غير محدد',
    synonyms_en: ['heart failure', 'chf', 'congestive heart failure'],
    synonyms_ar: ['قصور القلب', 'فشل القلب', 'قصور القلب الاحتقاني'],
    base_confidence: 0.88,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '194',
    specificity_modifiers: [
      {
        id: 'hf_type',
        keywords_en: ['systolic', 'diastolic', 'acute on chronic', 'ejection fraction'],
        keywords_ar: ['انقباضي', 'انبساطي', 'حاد على مزمن', 'الكسر القذفي'],
        prompt_en: 'Specify heart failure type (systolic/diastolic, acute vs. chronic) for a more specific code.',
        prompt_ar: 'يرجى تحديد نوع قصور القلب (انقباضي/انبساطي، حاد أو مزمن) لترميز أكثر دقة.',
        severity: 'warning',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'R05',
    desc_en: 'Cough',
    desc_ar: 'سعال',
    synonyms_en: ['cough'],
    synonyms_ar: ['سعال', 'كحة'],
    base_confidence: 0.6,
    soi_weight: 0,
    rom_weight: 0,
    drg_family: 'AMB',
  },
  {
    code: 'R50.9',
    desc_en: 'Fever, unspecified',
    desc_ar: 'حمى، غير محددة',
    synonyms_en: ['fever'],
    synonyms_ar: ['حمى', 'سخونة', 'حرارة مرتفعة'],
    base_confidence: 0.55,
    soi_weight: 0,
    rom_weight: 0,
    drg_family: 'AMB',
  },
  // --- Cardiovascular ---
  {
    code: 'I48.91',
    desc_en: 'Unspecified atrial fibrillation',
    desc_ar: 'الرجفان الأذيني غير المحدد',
    synonyms_en: ['atrial fibrillation', 'afib', 'a-fib', 'irregular heart rhythm'],
    synonyms_ar: ['الرجفان الأذيني', 'رجفان أذيني', 'عدم انتظام ضربات القلب'],
    base_confidence: 0.88,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '138',
    specificity_modifiers: [
      {
        id: 'afib_type',
        keywords_en: ['paroxysmal', 'persistent', 'permanent', 'chronic afib'],
        keywords_ar: ['نوبي', 'مستمر', 'دائم', 'رجفان مزمن'],
        prompt_en: 'Specify the type of atrial fibrillation (paroxysmal, persistent, or permanent).',
        prompt_ar: 'يرجى تحديد نوع الرجفان الأذيني (نوبي، مستمر، أو دائم).',
        severity: 'info',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'I46.9',
    desc_en: 'Cardiac arrest, cause unspecified',
    desc_ar: 'توقف القلب، السبب غير محدد',
    synonyms_en: ['cardiac arrest', 'cardiopulmonary arrest', 'code blue'],
    synonyms_ar: ['توقف القلب', 'سكتة قلبية', 'توقف قلبي رئوي'],
    base_confidence: 0.92,
    soi_weight: 3,
    rom_weight: 3,
    drg_family: '129',
    specificity_modifiers: [
      {
        id: 'cardiac_arrest_rosc',
        keywords_en: ['rosc', 'return of spontaneous circulation', 'resuscitated'],
        keywords_ar: ['عودة الدوران التلقائي', 'تم الإنعاش'],
        prompt_en: 'Document whether return of spontaneous circulation (ROSC) was achieved.',
        prompt_ar: 'يرجى توثيق ما إذا تم تحقيق عودة الدوران التلقائي (ROSC).',
        severity: 'critical',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'I26.99',
    desc_en: 'Other pulmonary embolism without acute cor pulmonale',
    desc_ar: 'الانصمام الرئوي الآخر دون القلب الرئوي الحاد',
    synonyms_en: ['pulmonary embolism', 'pe', 'blood clot in lung'],
    synonyms_ar: ['الانصمام الرئوي', 'جلطة رئوية', 'انسداد رئوي'],
    base_confidence: 0.88,
    soi_weight: 3,
    rom_weight: 3,
    drg_family: '175',
    specificity_modifiers: [
      {
        id: 'pe_severity',
        keywords_en: ['massive', 'submassive', 'right heart strain', 'hemodynamically unstable'],
        keywords_ar: ['شديد', 'إجهاد القلب الأيمن', 'عدم استقرار الدورة الدموية'],
        prompt_en: 'Specify severity (massive/submassive) or right heart strain for the pulmonary embolism.',
        prompt_ar: 'يرجى تحديد شدة الانصمام الرئوي (شديد/دون شديد) أو وجود إجهاد للقلب الأيمن.',
        severity: 'critical',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'I82.409',
    desc_en: 'Acute embolism and thrombosis of unspecified deep veins of unspecified lower extremity',
    desc_ar: 'خثار وانصمام حاد في الأوردة العميقة غير المحددة للطرف السفلي',
    synonyms_en: ['deep vein thrombosis', 'dvt', 'blood clot in leg'],
    synonyms_ar: ['خثار وريدي عميق', 'جلطة وريدية', 'جلطة في الساق'],
    base_confidence: 0.85,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '128',
  },
  {
    code: 'R55',
    desc_en: 'Syncope and collapse',
    desc_ar: 'الإغماء والانهيار',
    synonyms_en: ['syncope', 'fainting', 'passed out', 'collapse'],
    synonyms_ar: ['إغماء', 'فقدان الوعي', 'انهيار'],
    base_confidence: 0.8,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '056',
  },
  {
    code: 'R07.9',
    desc_en: 'Chest pain, unspecified',
    desc_ar: 'ألم في الصدر، غير محدد',
    synonyms_en: ['chest pain'],
    synonyms_ar: ['ألم في الصدر', 'ألم صدري'],
    base_confidence: 0.6,
    soi_weight: 0,
    rom_weight: 0,
    drg_family: '143',
  },
  // --- Respiratory ---
  {
    code: 'J96.00',
    desc_en: 'Acute respiratory failure, unspecified whether with hypoxia or hypercapnia',
    desc_ar: 'فشل تنفسي حاد، غير محدد إذا كان مصحوبًا بنقص الأكسجين أو فرط ثاني أكسيد الكربون',
    synonyms_en: ['respiratory failure', 'acute respiratory failure'],
    synonyms_ar: ['فشل تنفسي حاد', 'فشل تنفسي'],
    base_confidence: 0.87,
    soi_weight: 3,
    rom_weight: 3,
    drg_family: '131',
  },
  {
    code: 'J91.8',
    desc_en: 'Pleural effusion in other conditions classified elsewhere',
    desc_ar: 'الانصباب الجنبي في حالات أخرى',
    synonyms_en: ['pleural effusion', 'fluid around lung'],
    synonyms_ar: ['الانصباب الجنبي', 'سوائل حول الرئة'],
    base_confidence: 0.82,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '194',
  },
  {
    code: 'J81.0',
    desc_en: 'Acute pulmonary edema',
    desc_ar: 'وذمة رئوية حادة',
    synonyms_en: ['pulmonary edema', 'fluid in lungs'],
    synonyms_ar: ['وذمة رئوية', 'احتقان رئوي'],
    base_confidence: 0.85,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '194',
  },
  {
    code: 'U07.1',
    desc_en: 'COVID-19',
    desc_ar: 'كوفيد-19',
    synonyms_en: ['covid', 'covid-19', 'coronavirus', 'sars-cov-2'],
    synonyms_ar: ['كوفيد-19', 'فيروس كورونا', 'كورونا'],
    base_confidence: 0.9,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '780',
  },
  // --- Endocrine & Metabolic ---
  {
    code: 'E11.10',
    desc_en: 'Type 2 diabetes mellitus with ketoacidosis without coma',
    desc_ar: 'داء السكري من النوع الثاني مصحوب بالحماض الكيتوني دون غيبوبة',
    synonyms_en: ['diabetic ketoacidosis', 'dka'],
    synonyms_ar: ['الحماض الكيتوني السكري', 'حماض كيتوني سكري'],
    base_confidence: 0.9,
    soi_weight: 3,
    rom_weight: 3,
    drg_family: '468',
    // A note mentioning both generic "diabetes" and "DKA" would otherwise
    // code E11.9 ("without complications") alongside this — a direct
    // contradiction, since the same diabetes clearly does have a
    // complication. The more specific code always wins.
    supersedes: ['E11.9'],
  },
  {
    code: 'E16.2',
    desc_en: 'Hypoglycemia, unspecified',
    desc_ar: 'نقص سكر الدم، غير محدد',
    synonyms_en: ['hypoglycemia', 'low blood sugar'],
    synonyms_ar: ['نقص سكر الدم', 'هبوط السكر'],
    base_confidence: 0.85,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '420',
  },
  {
    code: 'E05.90',
    desc_en: 'Thyrotoxicosis, unspecified without thyrotoxic crisis or storm',
    desc_ar: 'التسمم الدرقي، غير محدد دون أزمة درقية',
    synonyms_en: ['hyperthyroidism', 'thyrotoxicosis', 'overactive thyroid'],
    synonyms_ar: ['فرط نشاط الغدة الدرقية', 'التسمم الدرقي'],
    base_confidence: 0.85,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '890',
  },
  {
    code: 'E03.9',
    desc_en: 'Hypothyroidism, unspecified',
    desc_ar: 'قصور الغدة الدرقية، غير محدد',
    synonyms_en: ['hypothyroidism', 'underactive thyroid'],
    synonyms_ar: ['قصور الغدة الدرقية', 'خمول الغدة الدرقية'],
    base_confidence: 0.87,
    soi_weight: 1,
    rom_weight: 0,
    drg_family: '890',
  },
  {
    code: 'E66.9',
    desc_en: 'Obesity, unspecified',
    desc_ar: 'السمنة، غير محددة',
    synonyms_en: ['obesity', 'overweight'],
    synonyms_ar: ['السمنة', 'زيادة الوزن'],
    base_confidence: 0.8,
    soi_weight: 0,
    rom_weight: 0,
    drg_family: '447',
  },
  {
    code: 'E87.1',
    desc_en: 'Hypo-osmolality and hyponatremia',
    desc_ar: 'نقص صوديوم الدم',
    synonyms_en: ['hyponatremia', 'low sodium'],
    synonyms_ar: ['نقص صوديوم الدم', 'انخفاض الصوديوم'],
    base_confidence: 0.84,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '895',
  },
  {
    code: 'E87.5',
    desc_en: 'Hyperkalemia',
    desc_ar: 'فرط بوتاسيوم الدم',
    synonyms_en: ['hyperkalemia', 'high potassium'],
    synonyms_ar: ['فرط بوتاسيوم الدم', 'ارتفاع البوتاسيوم'],
    base_confidence: 0.85,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '895',
  },
  {
    code: 'E86.0',
    desc_en: 'Dehydration',
    desc_ar: 'الجفاف',
    synonyms_en: ['dehydration', 'dehydrated'],
    synonyms_ar: ['الجفاف', 'جفاف الجسم'],
    base_confidence: 0.8,
    soi_weight: 1,
    rom_weight: 0,
    drg_family: '448',
  },
  {
    code: 'E46',
    desc_en: 'Unspecified protein-calorie malnutrition',
    desc_ar: 'سوء التغذية البروتيني السعراتي غير المحدد',
    synonyms_en: ['malnutrition'],
    synonyms_ar: ['سوء التغذية'],
    base_confidence: 0.82,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '449',
  },
  // --- Renal & Urinary ---
  {
    code: 'N17.9',
    desc_en: 'Acute kidney failure, unspecified',
    desc_ar: 'الفشل الكلوي الحاد، غير محدد',
    synonyms_en: ['acute kidney injury', 'aki', 'acute renal failure'],
    synonyms_ar: ['الفشل الكلوي الحاد', 'إصابة كلوية حادة'],
    base_confidence: 0.87,
    soi_weight: 3,
    rom_weight: 3,
    drg_family: '461',
    specificity_modifiers: [
      {
        id: 'aki_dialysis',
        keywords_en: ['dialysis', 'hemodialysis', 'stage', 'requiring dialysis'],
        keywords_ar: ['غسيل كلوي', 'يحتاج غسيل كلوي', 'المرحلة'],
        prompt_en: 'Document whether dialysis is required for this episode of acute kidney injury.',
        prompt_ar: 'يرجى توثيق ما إذا كانت هذه الحالة من الإصابة الكلوية الحادة تتطلب غسيلاً كلويًا.',
        severity: 'warning',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'N20.0',
    desc_en: 'Calculus of kidney',
    desc_ar: 'حصوة الكلى',
    synonyms_en: ['kidney stones', 'renal calculi', 'nephrolithiasis'],
    synonyms_ar: ['حصوات الكلى', 'حصى الكلى'],
    base_confidence: 0.88,
    soi_weight: 1,
    rom_weight: 0,
    drg_family: '465',
  },
  {
    code: 'R33.9',
    desc_en: 'Retention of urine, unspecified',
    desc_ar: 'احتباس البول، غير محدد',
    synonyms_en: ['urinary retention'],
    synonyms_ar: ['احتباس البول'],
    base_confidence: 0.83,
    soi_weight: 1,
    rom_weight: 0,
    drg_family: '466',
  },
  // --- Gastrointestinal ---
  {
    code: 'K81.9',
    desc_en: 'Cholecystitis, unspecified',
    desc_ar: 'التهاب المرارة، غير محدد',
    synonyms_en: ['cholecystitis', 'gallbladder inflammation'],
    synonyms_ar: ['التهاب المرارة'],
    base_confidence: 0.86,
    soi_weight: 2,
    rom_weight: 1,
    drg_family: '220',
  },
  {
    code: 'K85.90',
    desc_en: 'Acute pancreatitis without necrosis or infection, unspecified',
    desc_ar: 'التهاب البنكرياس الحاد دون نخر أو عدوى، غير محدد',
    synonyms_en: ['pancreatitis'],
    synonyms_ar: ['التهاب البنكرياس'],
    base_confidence: 0.85,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '221',
  },
  {
    code: 'K92.2',
    desc_en: 'Gastrointestinal hemorrhage, unspecified',
    desc_ar: 'نزيف الجهاز الهضمي، غير محدد',
    synonyms_en: ['gi bleed', 'gastrointestinal bleeding', 'gi hemorrhage'],
    synonyms_ar: ['نزيف الجهاز الهضمي', 'نزيف معوي'],
    base_confidence: 0.87,
    soi_weight: 3,
    rom_weight: 3,
    drg_family: '280',
    specificity_modifiers: [
      {
        id: 'gi_bleed_source',
        keywords_en: ['upper gi', 'lower gi', 'hematemesis', 'melena', 'hemodynamically unstable'],
        keywords_ar: ['علوي', 'سفلي', 'قيء دموي', 'براز أسود', 'عدم استقرار الدورة الدموية'],
        prompt_en: 'Specify the source (upper/lower GI) or hemodynamic status for the GI bleed.',
        prompt_ar: 'يرجى تحديد مصدر النزيف (علوي/سفلي) أو حالة الدورة الدموية.',
        severity: 'critical',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'K27.9',
    desc_en: 'Peptic ulcer, site unspecified, without hemorrhage or perforation',
    desc_ar: 'القرحة الهضمية، الموقع غير محدد، دون نزيف أو انثقاب',
    synonyms_en: ['peptic ulcer', 'stomach ulcer'],
    synonyms_ar: ['القرحة الهضمية', 'قرحة المعدة'],
    base_confidence: 0.83,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '282',
  },
  {
    code: 'K56.60',
    desc_en: 'Unspecified intestinal obstruction',
    desc_ar: 'انسداد معوي غير محدد',
    synonyms_en: ['bowel obstruction', 'intestinal obstruction'],
    synonyms_ar: ['انسداد معوي', 'انسداد الأمعاء'],
    base_confidence: 0.85,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '254',
    specificity_modifiers: [
      {
        id: 'bowel_obstruction_type',
        keywords_en: ['partial', 'complete', 'strangulated', 'strangulation'],
        keywords_ar: ['جزئي', 'كامل', 'اختناق'],
        prompt_en: 'Specify whether the obstruction is partial or complete, and whether strangulation is present.',
        prompt_ar: 'يرجى تحديد ما إذا كان الانسداد جزئيًا أو كاملاً، ووجود اختناق معوي من عدمه.',
        severity: 'warning',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'A09',
    desc_en: 'Infectious gastroenteritis and colitis, unspecified',
    desc_ar: 'التهاب المعدة والأمعاء المعدي، غير محدد',
    synonyms_en: ['gastroenteritis', 'stomach flu', 'food poisoning'],
    synonyms_ar: ['التهاب المعدة والأمعاء', 'تسمم غذائي'],
    base_confidence: 0.82,
    soi_weight: 1,
    rom_weight: 0,
    drg_family: '249',
  },
  {
    code: 'R10.9',
    desc_en: 'Unspecified abdominal pain',
    desc_ar: 'ألم بطني غير محدد',
    synonyms_en: ['abdominal pain', 'stomach pain'],
    synonyms_ar: ['ألم بطني', 'ألم في البطن'],
    base_confidence: 0.6,
    soi_weight: 0,
    rom_weight: 0,
    drg_family: '246',
  },
  {
    code: 'K75.9',
    desc_en: 'Inflammatory liver disease, unspecified',
    desc_ar: 'مرض التهاب الكبد، غير محدد',
    synonyms_en: ['hepatitis', 'liver inflammation'],
    synonyms_ar: ['التهاب الكبد'],
    base_confidence: 0.83,
    soi_weight: 2,
    rom_weight: 1,
    drg_family: '200',
  },
  {
    code: 'K74.60',
    desc_en: 'Unspecified cirrhosis of liver',
    desc_ar: 'تليف الكبد غير المحدد',
    synonyms_en: ['cirrhosis', 'liver cirrhosis'],
    synonyms_ar: ['تليف الكبد'],
    base_confidence: 0.86,
    soi_weight: 3,
    rom_weight: 3,
    drg_family: '205',
    specificity_modifiers: [
      {
        id: 'cirrhosis_decompensation',
        keywords_en: ['decompensated', 'compensated', 'ascites', 'varices', 'encephalopathy'],
        keywords_ar: ['غير معاوض', 'معاوض', 'استسقاء', 'دوالي', 'اعتلال دماغي'],
        prompt_en: 'Document decompensation status (ascites, varices, encephalopathy) for the cirrhosis.',
        prompt_ar: 'يرجى توثيق حالة المعاوضة (استسقاء، دوالي، اعتلال دماغي) لتليف الكبد.',
        severity: 'critical',
        soi_gain: 1,
      },
    ],
  },
  // --- Neurological ---
  {
    code: 'G40.909',
    desc_en: 'Epilepsy, unspecified, not intractable, without status epilepticus',
    desc_ar: 'الصرع، غير محدد، غير معند، دون حالة صرعية',
    synonyms_en: ['seizure', 'epilepsy', 'convulsion'],
    synonyms_ar: ['الصرع', 'نوبة تشنجية', 'تشنجات'],
    base_confidence: 0.85,
    soi_weight: 2,
    rom_weight: 1,
    drg_family: '065',
    specificity_modifiers: [
      {
        id: 'seizure_status',
        keywords_en: ['status epilepticus', 'intractable'],
        keywords_ar: ['حالة صرعية', 'معند'],
        prompt_en: 'Document whether status epilepticus or intractable epilepsy is present.',
        prompt_ar: 'يرجى توثيق ما إذا كانت هناك حالة صرعية مستمرة أو صرع معند.',
        severity: 'critical',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'G03.9',
    desc_en: 'Meningitis, unspecified',
    desc_ar: 'التهاب السحايا، غير محدد',
    synonyms_en: ['meningitis'],
    synonyms_ar: ['التهاب السحايا'],
    base_confidence: 0.88,
    soi_weight: 3,
    rom_weight: 3,
    drg_family: '070',
    specificity_modifiers: [
      {
        id: 'meningitis_organism',
        keywords_en: ['bacterial', 'viral', 'fungal'],
        keywords_ar: ['بكتيري', 'فيروسي', 'فطري'],
        prompt_en: 'Specify the causative organism type (bacterial, viral, fungal) for the meningitis.',
        prompt_ar: 'يرجى تحديد نوع العامل المسبب (بكتيري، فيروسي، فطري) لالتهاب السحايا.',
        severity: 'critical',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'G45.9',
    desc_en: 'Transient cerebral ischemic attack, unspecified',
    desc_ar: 'نوبة إقفارية دماغية عابرة، غير محددة',
    synonyms_en: ['tia', 'transient ischemic attack', 'mini-stroke'],
    synonyms_ar: ['نوبة إقفارية عابرة', 'سكتة دماغية عابرة'],
    base_confidence: 0.87,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '024',
  },
  {
    code: 'R51.9',
    desc_en: 'Headache, unspecified',
    desc_ar: 'صداع، غير محدد',
    synonyms_en: ['headache', 'migraine'],
    synonyms_ar: ['صداع', 'شقيقة'],
    base_confidence: 0.6,
    soi_weight: 0,
    rom_weight: 0,
    drg_family: '050',
  },
  {
    code: 'R42',
    desc_en: 'Dizziness and giddiness',
    desc_ar: 'دوخة ودوار',
    synonyms_en: ['dizziness', 'vertigo', 'lightheaded'],
    synonyms_ar: ['دوخة', 'دوار'],
    base_confidence: 0.6,
    soi_weight: 0,
    rom_weight: 0,
    drg_family: '056',
  },
  // --- Musculoskeletal ---
  {
    code: 'M19.90',
    desc_en: 'Osteoarthritis, unspecified site',
    desc_ar: 'الفصال العظمي، الموقع غير محدد',
    synonyms_en: ['osteoarthritis', 'joint degeneration'],
    synonyms_ar: ['الفصال العظمي', 'خشونة المفاصل'],
    base_confidence: 0.82,
    soi_weight: 0,
    rom_weight: 0,
    drg_family: '300',
  },
  {
    code: 'M54.9',
    desc_en: 'Dorsalgia, unspecified',
    desc_ar: 'ألم الظهر، غير محدد',
    synonyms_en: ['back pain', 'lower back pain'],
    synonyms_ar: ['ألم الظهر', 'آلام أسفل الظهر'],
    base_confidence: 0.6,
    soi_weight: 0,
    rom_weight: 0,
    drg_family: '301',
  },
  {
    code: 'T14.90XA',
    desc_en: 'Injury, unspecified, initial encounter',
    desc_ar: 'إصابة غير محددة، الزيارة الأولى',
    synonyms_en: ['soft tissue injury', 'sprain', 'strain'],
    synonyms_ar: ['إصابة الأنسجة الرخوة', 'التواء', 'شد عضلي'],
    base_confidence: 0.65,
    soi_weight: 0,
    rom_weight: 0,
    drg_family: '310',
  },
  {
    code: 'T30.0',
    desc_en: 'Burn of unspecified body region, unspecified degree',
    desc_ar: 'حرق في منطقة غير محددة من الجسم، درجة غير محددة',
    synonyms_en: ['burn', 'burns'],
    synonyms_ar: ['حرق', 'حروق'],
    base_confidence: 0.8,
    soi_weight: 2,
    rom_weight: 1,
    drg_family: '350',
  },
  // --- Infectious Disease ---
  {
    code: 'L03.90',
    desc_en: 'Cellulitis, unspecified',
    desc_ar: 'التهاب النسيج الخلوي، غير محدد',
    synonyms_en: ['cellulitis', 'skin infection'],
    synonyms_ar: ['التهاب النسيج الخلوي', 'عدوى جلدية'],
    base_confidence: 0.85,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '383',
  },
  {
    code: 'M86.9',
    desc_en: 'Osteomyelitis, unspecified',
    desc_ar: 'التهاب العظم والنقي، غير محدد',
    synonyms_en: ['osteomyelitis', 'bone infection'],
    synonyms_ar: ['التهاب العظم والنقي', 'عدوى العظام'],
    base_confidence: 0.84,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '384',
    specificity_modifiers: [
      {
        id: 'osteomyelitis_chronicity',
        keywords_en: ['acute', 'chronic'],
        keywords_ar: ['حاد', 'مزمن'],
        prompt_en: 'Specify whether the osteomyelitis is acute or chronic.',
        prompt_ar: 'يرجى تحديد ما إذا كان التهاب العظم والنقي حادًا أم مزمنًا.',
        severity: 'info',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'A15.9',
    desc_en: 'Respiratory tuberculosis, unspecified',
    desc_ar: 'السل الرئوي، غير محدد',
    synonyms_en: ['tuberculosis', 'tb'],
    synonyms_ar: ['السل', 'الدرن'],
    base_confidence: 0.86,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '790',
  },
  // --- Hematology & Oncology ---
  {
    code: 'D64.9',
    desc_en: 'Anemia, unspecified',
    desc_ar: 'فقر الدم، غير محدد',
    synonyms_en: ['anemia'],
    synonyms_ar: ['فقر الدم', 'أنيميا'],
    base_confidence: 0.83,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '660',
  },
  {
    code: 'C80.1',
    desc_en: 'Malignant (primary) neoplasm, unspecified',
    desc_ar: 'ورم خبيث (أولي)، غير محدد',
    synonyms_en: ['cancer', 'malignancy', 'tumor', 'neoplasm'],
    synonyms_ar: ['سرطان', 'ورم خبيث'],
    base_confidence: 0.82,
    soi_weight: 3,
    rom_weight: 3,
    drg_family: '690',
    specificity_modifiers: [
      {
        id: 'malignancy_site_stage',
        keywords_en: ['primary site', 'stage', 'metastatic', 'metastasis'],
        keywords_ar: ['الموقع الأولي', 'المرحلة', 'ورم منتشر', 'انتشار'],
        prompt_en: 'Document the primary site and stage (or metastatic status) for accurate oncology coding.',
        prompt_ar: 'يرجى توثيق الموقع الأولي والمرحلة (أو حالة الانتشار) لترميز دقيق للأورام.',
        severity: 'warning',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'Z51.11',
    desc_en: 'Encounter for antineoplastic chemotherapy',
    desc_ar: 'زيارة للعلاج الكيميائي المضاد للأورام',
    synonyms_en: ['chemotherapy', 'chemo'],
    synonyms_ar: ['العلاج الكيميائي', 'جلسة كيماوي'],
    base_confidence: 0.9,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '691',
  },
  // --- Obstetrics & Gynecology ---
  {
    code: 'O80',
    desc_en: 'Encounter for full-term uncomplicated delivery',
    desc_ar: 'زيارة للولادة الطبيعية الكاملة دون مضاعفات',
    synonyms_en: ['normal delivery', 'vaginal delivery', 'childbirth'],
    synonyms_ar: ['ولادة طبيعية', 'ولادة مهبلية'],
    base_confidence: 0.9,
    soi_weight: 0,
    rom_weight: 0,
    drg_family: '560',
  },
  {
    code: 'O82',
    desc_en: 'Encounter for cesarean delivery without indication',
    desc_ar: 'زيارة للولادة القيصرية',
    synonyms_en: ['cesarean', 'c-section', 'caesarean'],
    synonyms_ar: ['ولادة قيصرية', 'عملية قيصرية'],
    base_confidence: 0.9,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '561',
    // A note describing a labor that converted to cesarean ("attempted
    // vaginal delivery, converted to emergency cesarean") would otherwise
    // match both O80 (normal delivery) and O82 — but the delivery that
    // actually happened was the cesarean, so it wins.
    supersedes: ['O80'],
  },
  {
    code: 'O14.90',
    desc_en: 'Unspecified pre-eclampsia, unspecified trimester',
    desc_ar: 'تسمم الحمل غير المحدد',
    synonyms_en: ['preeclampsia', 'pre-eclampsia', 'pregnancy hypertension'],
    synonyms_ar: ['تسمم الحمل', 'ما قبل الإرجاج'],
    base_confidence: 0.85,
    soi_weight: 2,
    rom_weight: 2,
    drg_family: '570',
    specificity_modifiers: [
      {
        id: 'preeclampsia_severity',
        keywords_en: ['severe features', 'with severe', 'without severe'],
        keywords_ar: ['سمات شديدة', 'مصحوب بشدة', 'دون شدة'],
        prompt_en: 'Document whether severe features are present for the pre-eclampsia.',
        prompt_ar: 'يرجى توثيق ما إذا كانت هناك سمات شديدة مصاحبة لتسمم الحمل.',
        severity: 'critical',
        soi_gain: 1,
      },
    ],
  },
  {
    code: 'O03.9',
    desc_en: 'Complete or unspecified spontaneous abortion without complication',
    desc_ar: 'إجهاض تلقائي كامل أو غير محدد دون مضاعفات',
    synonyms_en: ['miscarriage', 'spontaneous abortion'],
    synonyms_ar: ['إجهاض', 'إجهاض تلقائي'],
    base_confidence: 0.85,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '580',
  },
  // --- Psychiatric ---
  {
    code: 'F32.9',
    desc_en: 'Major depressive disorder, single episode, unspecified',
    desc_ar: 'اضطراب اكتئابي كبير، نوبة واحدة، غير محدد',
    synonyms_en: ['depression', 'depressive disorder'],
    synonyms_ar: ['الاكتئاب', 'اضطراب اكتئابي'],
    base_confidence: 0.8,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '750',
  },
  {
    code: 'F41.9',
    desc_en: 'Anxiety disorder, unspecified',
    desc_ar: 'اضطراب القلق، غير محدد',
    synonyms_en: ['anxiety', 'anxiety disorder'],
    synonyms_ar: ['القلق', 'اضطراب القلق'],
    base_confidence: 0.78,
    soi_weight: 0,
    rom_weight: 0,
    drg_family: '751',
  },
  {
    code: 'F19.10',
    desc_en: 'Other psychoactive substance abuse, uncomplicated',
    desc_ar: 'تعاطي مواد نفسية أخرى، دون مضاعفات',
    synonyms_en: ['substance abuse', 'drug abuse', 'substance use disorder'],
    synonyms_ar: ['تعاطي المخدرات', 'اضطراب تعاطي المواد'],
    base_confidence: 0.78,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '755',
  },
  // --- Pediatric ---
  {
    code: 'P59.9',
    desc_en: 'Neonatal jaundice, unspecified',
    desc_ar: 'اليرقان الوليدي، غير محدد',
    synonyms_en: ['neonatal jaundice', 'newborn jaundice'],
    synonyms_ar: ['اليرقان الوليدي', 'صفار المولود'],
    base_confidence: 0.85,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '630',
  },
  {
    code: 'R56.00',
    desc_en: 'Simple febrile convulsions',
    desc_ar: 'التشنجات الحرارية البسيطة',
    synonyms_en: ['febrile seizure', 'febrile convulsion'],
    synonyms_ar: ['التشنج الحروري', 'تشنجات الحمى'],
    base_confidence: 0.85,
    soi_weight: 1,
    rom_weight: 0,
    drg_family: '631',
  },
  {
    code: 'J21.9',
    desc_en: 'Acute bronchiolitis, unspecified',
    desc_ar: 'التهاب القصيبات الحاد، غير محدد',
    synonyms_en: ['bronchiolitis'],
    synonyms_ar: ['التهاب القصيبات'],
    base_confidence: 0.84,
    soi_weight: 1,
    rom_weight: 1,
    drg_family: '632',
  },
];
/** Words that negate a match in either language (handled by the NLU tokenizer).
 * Includes both pre-term phrasing ("no fever", "denies chest pain") and
 * post-term phrasing ("myocardial infarction ruled out", "sepsis excluded",
 * "pneumonia unlikely") — the matcher checks both sides of the match. */
export const NEGATION_TERMS_EN = [
  'no', 'not', 'denies', 'denied', 'without', 'ruled out', 'negative for',
  'excluded', 'unlikely', 'resolved', 'absent', 'not detected', 'not present', 'not found',
];
export const NEGATION_TERMS_AR = ['لا يوجد', 'ينفي', 'بدون', 'سلبي', 'استبعاد', 'غير موجود', 'غائب', 'سالب'];
/** Words that mark a diagnosis as suspected rather than confirmed, lowering confidence. */
export const UNCERTAINTY_TERMS_EN = ['suspected', 'possible', 'probable', 'rule out', 'query'];
export const UNCERTAINTY_TERMS_AR = ['يشتبه', 'محتمل', 'مرجح', 'استبعاد'];
export function findLexiconEntry(code: string): LexiconEntry | undefined {
  return BILINGUAL_LEXICON.find((e) => e.code === code);
}
