import type { User, Chat, ChatMessage, Patient, Claim, Encounter, AuditLog, Payment } from './types';
export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'User A' },
  { id: 'u2', name: 'User B' }
];
export const MOCK_CHATS: Chat[] = [
  { id: 'c1', title: 'General' },
];
export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  { id: 'm1', chatId: 'c1', userId: 'u1', text: 'Hello', ts: Date.now() },
];
// --- BRAINSAIT DRG SUITE MOCK DATA ---
// Deliberately code-switched (mixed Arabic/English) clinical notes,
// reflecting real Saudi documentation patterns, used to seed and demo the
// bilingual coding engine.
export const MOCK_CLINICAL_NOTES: string[] = [
  'Patient with sukari symptoms, no complications noted.',
  'High blood pressure diagnosed, ضغط دم مرتفع controlled with medication.',
  'Appendix pain and inflammation, suspected appendicitis.',
  'Left leg fracture after fall, كسر in tibia.',
  'Routine check for hypertension, well controlled, no crisis.',
  'Pneumonia with bacterial organism suspected. سعال شديد reported.',
  'UTI with catheter association.',
  'Myocardial infarction STEMI confirmed.',
  'Hypertension crisis, I10 code needed.',
  'Diabetes type 2, E11.9 unspecified, with diabetic nephropathy.',
  'Patient presents with classic signs of acute myocardial infarction. EKG confirms.',
  'Diagnosis of appendicitis confirmed by imaging. ألم الزائدة is severe with perforation.',
  'Patient complains of cough and fever. Suspected pneumonia.',
  'مريض يعاني من التهاب رئوي بكتيري وكسر في الساق اليسرى.',
  'المريض حالة معروفة بداء السكري ويأتي للمراجعة الروتينية دون مضاعفات.',
  'Patient underwent appendectomy for acute appendicitis with perforation.',
  'مريض تم له استئصال المرارة بسبب التهاب المرارة الحاد.',
];
export const MOCK_PATIENTS: Patient[] = [
  { id: 'p1', national_id: '1012345678', given_name: 'Fatima', family_name: 'Al-Fahad' },
  { id: 'p2', national_id: '1023456789', given_name: 'Mohammed', family_name: 'Al-Ghamdi' },
  { id: 'p3', national_id: '1034567890', given_name: 'Aisha', family_name: 'Al-Qahtani' },
  { id: 'p4', national_id: '1045678901', given_name: 'Khaled', family_name: 'Al-Mutairi' },
  { id: 'p5', national_id: '1056789012', given_name: 'Noura', family_name: 'Al-Dosari' },
];
export const MOCK_ENCOUNTERS: Encounter[] = [
    { id: 'e1', patient_id: 'p1', encounter_type: 'INPATIENT', admission_dt: new Date('2024-08-01T10:00:00Z').toISOString() },
    { id: 'e2', patient_id: 'p2', encounter_type: 'OUTPATIENT', admission_dt: new Date('2024-08-02T11:30:00Z').toISOString() },
    { id: 'e3', patient_id: 'p3', encounter_type: 'ED', admission_dt: new Date('2024-08-03T14:00:00Z').toISOString() },
    { id: 'e4', patient_id: 'p4', encounter_type: 'INPATIENT', admission_dt: new Date('2024-08-04T09:00:00Z').toISOString() },
    { id: 'e5', patient_id: 'p5', encounter_type: 'INPATIENT', admission_dt: new Date('2024-08-05T18:00:00Z').toISOString() },
];
export const MOCK_CLAIMS: Claim[] = [
  { id: 'cl1', encounter_id: 'e1', claim_number: 'CLM-2024-001', status: 'FC_3', submitted_at: new Date('2024-08-02T10:00:00Z').toISOString(), amount: 12500.50 },
  { id: 'cl2', encounter_id: 'e2', claim_number: 'CLM-2024-002', status: 'SENT', submitted_at: new Date('2024-08-03T11:30:00Z').toISOString(), amount: 850.00 },
  { id: 'cl3', encounter_id: 'e3', claim_number: 'CLM-2024-003', status: 'REJECTED', submitted_at: new Date('2024-08-04T14:00:00Z').toISOString(), amount: 1200.75 },
  { id: 'cl4', encounter_id: 'e4', claim_number: 'CLM-2024-004', status: 'NEEDS_REVIEW', submitted_at: null, amount: 25000.00 },
  { id: 'cl5', encounter_id: 'e5', claim_number: 'CLM-2024-005', status: 'DRAFT', submitted_at: null, amount: 18000.00 },
  { id: 'cl6', encounter_id: 'e1', claim_number: 'CLM-2024-006', status: 'DRAFT', submitted_at: null, amount: 9500.00 },
  { id: 'cl7', encounter_id: 'e2', claim_number: 'CLM-2024-007', status: 'FC_3', submitted_at: new Date('2024-08-05T12:00:00Z').toISOString(), amount: 450.25 },
  { id: 'cl8', encounter_id: 'e3', claim_number: 'CLM-2024-008', status: 'SENT', submitted_at: new Date('2024-08-06T15:00:00Z').toISOString(), amount: 1500.00 },
  { id: 'cl9', encounter_id: 'e4', claim_number: 'CLM-2024-009', status: 'NEEDS_REVIEW', submitted_at: null, amount: 32000.00 },
  { id: 'cl10', encounter_id: 'e5', claim_number: 'CLM-2024-010', status: 'DRAFT', submitted_at: null, amount: 21000.00 },
];
// --- SEED CODING JOBS: generated by the real bilingual engine, not hand-authored ---
// Every job below runs the exact same `runCodingEngine` / `classifyAutomationPhase`
// pipeline used in production (`worker/user-routes.ts`), so seed/demo data can
// never drift from the engine's actual behavior. The pass itself runs once,
// at build time (`bun run generate:seed`, see scripts/generate-seed-data.ts) —
// not inside the Worker. Running ~85 lexicon entries x 17 notes of regex
// matching live on every cold start/request blew past Cloudflare Workers'
// startup and per-request CPU budgets; baking the output into a static
// generated module keeps runtime cost at zero while still guaranteeing the
// seed data can never drift from actual engine behavior.
export interface NotePlan {
  encounter_id: string;
  note: string;
  visit_complexity?: string;
  encounter_type?: 'INPATIENT' | 'OUTPATIENT' | 'ED';
  age?: number;
}
export const NOTE_PLAN: NotePlan[] = [
  { encounter_id: 'e1', note: MOCK_CLINICAL_NOTES[5], encounter_type: 'INPATIENT', age: 58 }, // pneumonia + سعال شديد
  { encounter_id: 'e2', note: MOCK_CLINICAL_NOTES[10], encounter_type: 'ED', age: 61 }, // classic MI
  { encounter_id: 'e3', note: MOCK_CLINICAL_NOTES[11], encounter_type: 'ED', age: 34 }, // appendicitis with perforation
  { encounter_id: 'e4', note: MOCK_CLINICAL_NOTES[3], encounter_type: 'INPATIENT', age: 45 }, // left leg fracture
  { encounter_id: 'e5', note: MOCK_CLINICAL_NOTES[6], encounter_type: 'INPATIENT', age: 72 }, // UTI catheter
  { encounter_id: 'e1', note: MOCK_CLINICAL_NOTES[4], visit_complexity: 'low-complexity outpatient', encounter_type: 'OUTPATIENT', age: 50 }, // hypertension, autonomous-eligible
  { encounter_id: 'e2', note: MOCK_CLINICAL_NOTES[12], encounter_type: 'OUTPATIENT', age: 40 }, // cough/fever
  { encounter_id: 'e3', note: MOCK_CLINICAL_NOTES[9], encounter_type: 'INPATIENT', age: 55 }, // diabetes with nephropathy
  { encounter_id: 'e4', note: MOCK_CLINICAL_NOTES[1], encounter_type: 'OUTPATIENT', age: 63 }, // hypertension code-switched
  { encounter_id: 'e5', note: MOCK_CLINICAL_NOTES[0], encounter_type: 'OUTPATIENT', age: 47 }, // sukari
  { encounter_id: 'e1', note: MOCK_CLINICAL_NOTES[13], encounter_type: 'INPATIENT', age: 66 }, // Arabic-only: pneumonia + fracture
  { encounter_id: 'e2', note: MOCK_CLINICAL_NOTES[14], visit_complexity: 'low-complexity outpatient', encounter_type: 'OUTPATIENT', age: 39 }, // Arabic-only diabetes routine
  { encounter_id: 'e3', note: MOCK_CLINICAL_NOTES[2], encounter_type: 'ED', age: 29 }, // appendicitis suspected
  { encounter_id: 'e4', note: MOCK_CLINICAL_NOTES[7], encounter_type: 'ED', age: 68 }, // STEMI
  { encounter_id: 'e5', note: MOCK_CLINICAL_NOTES[8], encounter_type: 'ED', age: 59 }, // hypertension crisis
  { encounter_id: 'e1', note: MOCK_CLINICAL_NOTES[15], encounter_type: 'INPATIENT', age: 33 }, // appendectomy -> Surgical partition
  { encounter_id: 'e2', note: MOCK_CLINICAL_NOTES[16], encounter_type: 'INPATIENT', age: 52 }, // Arabic-only: cholecystectomy -> Surgical partition
];
export { MOCK_CODING_JOBS, MOCK_NUDGES, MOCK_ANALYTICS } from './seed-data.generated';
export const MOCK_AUDIT_LOGS: AuditLog[] = [
    { id: 'al1', actor: 'system', action: 'claim.submitted', object_type: 'claim', object_id: 'cl2', occurred_at: new Date().toISOString() },
    { id: 'al2', actor: 'user:coder@hospital.sa', action: 'coding_job.reviewed', object_type: 'coding_job', object_id: 'job1', occurred_at: new Date(Date.now() - 3600000).toISOString() },
    { id: 'al3', actor: 'system', action: 'nphies.token_refreshed', object_type: 'integration', object_id: 'nphies', occurred_at: new Date(Date.now() - 7200000).toISOString() },
    { id: 'al4', actor: 'system', action: 'claim.status_updated', object_type: 'claim', object_id: 'cl3', occurred_at: new Date(Date.now() - 10800000).toISOString() },
    { id: 'al5', actor: 'user:admin@brainsait.sa', action: 'user.login', object_type: 'user', object_id: 'admin@brainsait.sa', occurred_at: new Date(Date.now() - 14400000).toISOString() },
];
export const MOCK_PAYMENTS: Payment[] = [
    { id: 'pay1', claim_id: 'cl1', amount: 12500.50, currency: 'SAR', reconciled: true, received_at: new Date().toISOString() },
    { id: 'pay2', claim_id: 'cl7', amount: 450.25, currency: 'SAR', reconciled: true, received_at: new Date(Date.now() - 86400000).toISOString() },
    { id: 'pay3', claim_id: 'cl2', amount: 850.00, currency: 'SAR', reconciled: false, received_at: new Date(Date.now() - 172800000).toISOString() },
    { id: 'pay4', claim_id: 'cl8', amount: 1500.00, currency: 'SAR', reconciled: false, received_at: new Date(Date.now() - 259200000).toISOString() },
];
