/**
 * AUTO-GENERATED by scripts/generate-seed-data.ts. Do not edit by hand.
 * Regenerate with `bun run generate:seed` after changing NOTE_PLAN, the
 * bilingual lexicon, or the coding/DRG engine.
 */
import type { CodingJob, Nudge, Analytics, Account } from './types';

export const MOCK_CODING_JOBS: CodingJob[] = [
  {
    "id": "job1",
    "encounter_id": "e1",
    "suggested_codes": [
      {
        "code": "J18.9",
        "desc": "Pneumonia, unspecified organism",
        "desc_ar": "التهاب رئوي، غير محدد المسبب",
        "term_en": "pneumonia",
        "matched_text": "pneumonia",
        "confidence": 0.85,
        "is_principal": true,
        "soi_weight": 2,
        "rom_weight": 2
      },
      {
        "code": "R05",
        "desc": "Cough",
        "desc_ar": "سعال",
        "term_ar": "سعال",
        "matched_text": "سعال",
        "confidence": 0.45,
        "is_principal": false,
        "soi_weight": 0,
        "rom_weight": 0
      }
    ],
    "suggested_procedures": [],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.65,
    "phase": "CAC",
    "created_at": "2026-07-15T13:47:17.109Z",
    "source_text": "Pneumonia with bacterial organism suspected. سعال شديد reported.",
    "principal_code": "J18.9",
    "secondary_codes": [
      "R05"
    ],
    "drg": {
      "code": "194",
      "title_en": "Cardiopulmonary Medical Management",
      "title_ar": "الإدارة الطبية لأمراض القلب والرئة",
      "department_en": "Internal Medicine",
      "department_ar": "الطب الباطني",
      "soi": 2,
      "rom": 2,
      "relative_weight": 0.95,
      "subclass": "194-M-2",
      "methodology": "BrainSAIT-APR-DRG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Pneumonia, unspecified organism\" (J18.9) anchors DRG family 194 and contributes 1 SOI / 1 ROM point(s).",
          "1 secondary diagnosis(es) (R05) add 0 SOI / 0 ROM point(s).",
          "Severity score 1 → SOI tier 2; mortality score 1 → ROM tier 2.",
          "No matching OR procedure detected → Medical partition, relative weight 0.95."
        ],
        "ar": [
          "التشخيص الأساسي \"التهاب رئوي، غير محدد المسبب\" (J18.9) يحدد فئة DRG رقم 194 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "1 تشخيص(ات) ثانوية (R05) تضيف 0 نقطة شدة و 0 نقطة خطر وفاة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 1 ← المستوى 2.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 0.95."
        ]
      }
    },
    "detected_language": "mixed"
  },
  {
    "id": "job2",
    "encounter_id": "e2",
    "suggested_codes": [
      {
        "code": "I21.9",
        "desc": "Acute myocardial infarction, unspecified",
        "desc_ar": "احتشاء عضلة القلب الحاد، غير محدد",
        "term_en": "myocardial infarction",
        "matched_text": "myocardial infarction",
        "confidence": 0.9,
        "is_principal": true,
        "soi_weight": 3,
        "rom_weight": 3
      }
    ],
    "suggested_procedures": [],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.9,
    "phase": "CAC",
    "created_at": "2026-07-15T12:47:17.117Z",
    "source_text": "Patient presents with classic signs of acute myocardial infarction. EKG confirms.",
    "principal_code": "I21.9",
    "secondary_codes": [],
    "drg": {
      "code": "190",
      "title_en": "Acute Myocardial Infarction",
      "title_ar": "احتشاء عضلة القلب الحاد",
      "department_en": "Cardiology",
      "department_ar": "أمراض القلب",
      "soi": 2,
      "rom": 2,
      "relative_weight": 1.6,
      "subclass": "190-M-2",
      "methodology": "BrainSAIT-APR-DRG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Acute myocardial infarction, unspecified\" (I21.9) anchors DRG family 190 and contributes 2 SOI / 2 ROM point(s).",
          "Severity score 2 → SOI tier 2; mortality score 2 → ROM tier 2.",
          "No matching OR procedure detected → Medical partition, relative weight 1.6."
        ],
        "ar": [
          "التشخيص الأساسي \"احتشاء عضلة القلب الحاد، غير محدد\" (I21.9) يحدد فئة DRG رقم 190 ويساهم بـ 2 نقطة شدة و 2 نقطة خطر وفاة.",
          "درجة الشدة 2 ← المستوى 2؛ درجة خطر الوفاة 2 ← المستوى 2.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 1.6."
        ]
      }
    },
    "detected_language": "en"
  },
  {
    "id": "job3",
    "encounter_id": "e3",
    "suggested_codes": [
      {
        "code": "K37",
        "desc": "Unspecified appendicitis",
        "desc_ar": "التهاب الزائدة الدودية غير المحدد",
        "term_en": "appendicitis",
        "matched_text": "appendicitis",
        "confidence": 0.9,
        "is_principal": true,
        "soi_weight": 1,
        "rom_weight": 1
      }
    ],
    "suggested_procedures": [],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.9,
    "phase": "CAC",
    "created_at": "2026-07-15T11:47:17.119Z",
    "source_text": "Diagnosis of appendicitis confirmed by imaging. ألم الزائدة is severe with perforation.",
    "principal_code": "K37",
    "secondary_codes": [],
    "drg": {
      "code": "261",
      "title_en": "Appendectomy & Appendiceal Conditions",
      "title_ar": "استئصال الزائدة الدودية وحالاتها",
      "department_en": "General Surgery",
      "department_ar": "الجراحة العامة",
      "soi": 2,
      "rom": 2,
      "relative_weight": 0.8,
      "subclass": "261-M-2",
      "methodology": "BrainSAIT-APR-DRG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Unspecified appendicitis\" (K37) anchors DRG family 261 and contributes 1 SOI / 1 ROM point(s).",
          "Severity score 1 → SOI tier 2; mortality score 1 → ROM tier 2.",
          "No matching OR procedure detected → Medical partition, relative weight 0.8."
        ],
        "ar": [
          "التشخيص الأساسي \"التهاب الزائدة الدودية غير المحدد\" (K37) يحدد فئة DRG رقم 261 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 1 ← المستوى 2.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 0.8."
        ]
      }
    },
    "detected_language": "mixed"
  },
  {
    "id": "job4",
    "encounter_id": "e4",
    "suggested_codes": [
      {
        "code": "S82.202A",
        "desc": "Unspecified fracture of shaft of left tibia, initial encounter",
        "desc_ar": "كسر غير محدد في جسم عظمة الظنبوب اليسرى، الزيارة الأولى",
        "term_en": "left leg fracture",
        "matched_text": "left leg fracture",
        "confidence": 0.88,
        "is_principal": true,
        "soi_weight": 1,
        "rom_weight": 0
      }
    ],
    "suggested_procedures": [],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.88,
    "phase": "CAC",
    "created_at": "2026-07-15T10:47:17.123Z",
    "source_text": "Left leg fracture after fall, كسر in tibia.",
    "principal_code": "S82.202A",
    "secondary_codes": [],
    "drg": {
      "code": "302",
      "title_en": "Fractures & Musculoskeletal Trauma",
      "title_ar": "الكسور وإصابات الجهاز العضلي الهيكلي",
      "department_en": "Orthopedics",
      "department_ar": "جراحة العظام",
      "soi": 2,
      "rom": 1,
      "relative_weight": 0.75,
      "subclass": "302-M-2",
      "methodology": "BrainSAIT-APR-DRG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Unspecified fracture of shaft of left tibia, initial encounter\" (S82.202A) anchors DRG family 302 and contributes 1 SOI / 0 ROM point(s).",
          "Severity score 1 → SOI tier 2; mortality score 0 → ROM tier 1.",
          "No matching OR procedure detected → Medical partition, relative weight 0.75."
        ],
        "ar": [
          "التشخيص الأساسي \"كسر غير محدد في جسم عظمة الظنبوب اليسرى، الزيارة الأولى\" (S82.202A) يحدد فئة DRG رقم 302 ويساهم بـ 1 نقطة شدة و 0 نقطة خطر وفاة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 0 ← المستوى 1.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 0.75."
        ]
      }
    },
    "detected_language": "mixed"
  },
  {
    "id": "job5",
    "encounter_id": "e5",
    "suggested_codes": [
      {
        "code": "N39.0",
        "desc": "Urinary tract infection, site not specified",
        "desc_ar": "التهاب المسالك البولية، الموضع غير محدد",
        "term_en": "uti",
        "matched_text": "uti",
        "confidence": 0.8,
        "is_principal": true,
        "soi_weight": 1,
        "rom_weight": 1
      }
    ],
    "suggested_procedures": [],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.8,
    "phase": "CAC",
    "created_at": "2026-07-15T09:47:17.123Z",
    "source_text": "UTI with catheter association.",
    "principal_code": "N39.0",
    "secondary_codes": [],
    "drg": {
      "code": "466",
      "title_en": "Urinary Tract Infection",
      "title_ar": "التهاب المسالك البولية",
      "department_en": "Urology",
      "department_ar": "المسالك البولية",
      "soi": 2,
      "rom": 2,
      "relative_weight": 0.65,
      "subclass": "466-M-2",
      "methodology": "BrainSAIT-APR-DRG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Urinary tract infection, site not specified\" (N39.0) anchors DRG family 466 and contributes 1 SOI / 1 ROM point(s).",
          "Age 72 (≥65) adds 1 ROM point.",
          "Severity score 1 → SOI tier 2; mortality score 2 → ROM tier 2.",
          "No matching OR procedure detected → Medical partition, relative weight 0.65."
        ],
        "ar": [
          "التشخيص الأساسي \"التهاب المسالك البولية، الموضع غير محدد\" (N39.0) يحدد فئة DRG رقم 466 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "العمر 72 (≥65) يضيف نقطة خطر وفاة واحدة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 2 ← المستوى 2.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 0.65."
        ]
      }
    },
    "detected_language": "en"
  },
  {
    "id": "job6",
    "encounter_id": "e1",
    "suggested_codes": [
      {
        "code": "I10",
        "desc": "Essential (primary) hypertension",
        "desc_ar": "ارتفاع ضغط الدم الأساسي (الأولي)",
        "term_en": "hypertension",
        "matched_text": "hypertension",
        "confidence": 0.99,
        "is_principal": true,
        "soi_weight": 1,
        "rom_weight": 1
      }
    ],
    "suggested_procedures": [],
    "status": "SENT_TO_NPHIES",
    "confidence_score": 0.99,
    "phase": "AUTONOMOUS",
    "created_at": "2026-07-15T08:47:17.124Z",
    "source_text": "Routine check for hypertension, well controlled, no crisis.",
    "principal_code": "I10",
    "secondary_codes": [],
    "drg": {
      "code": "201",
      "title_en": "Hypertension",
      "title_ar": "ارتفاع ضغط الدم",
      "department_en": "Cardiology",
      "department_ar": "أمراض القلب",
      "soi": 2,
      "rom": 2,
      "relative_weight": 0.6,
      "subclass": "201-M-2",
      "methodology": "BrainSAIT-EAPG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Essential (primary) hypertension\" (I10) anchors DRG family 201 and contributes 1 SOI / 1 ROM point(s).",
          "Severity score 1 → SOI tier 2; mortality score 1 → ROM tier 2.",
          "No matching OR procedure detected → Medical partition, relative weight 0.6."
        ],
        "ar": [
          "التشخيص الأساسي \"ارتفاع ضغط الدم الأساسي (الأولي)\" (I10) يحدد فئة DRG رقم 201 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 1 ← المستوى 2.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 0.6."
        ]
      }
    },
    "detected_language": "en"
  },
  {
    "id": "job7",
    "encounter_id": "e2",
    "suggested_codes": [
      {
        "code": "J18.9",
        "desc": "Pneumonia, unspecified organism",
        "desc_ar": "التهاب رئوي، غير محدد المسبب",
        "term_en": "pneumonia",
        "matched_text": "pneumonia",
        "confidence": 0.7,
        "is_principal": true,
        "soi_weight": 2,
        "rom_weight": 2
      },
      {
        "code": "R05",
        "desc": "Cough",
        "desc_ar": "سعال",
        "term_en": "cough",
        "matched_text": "cough",
        "confidence": 0.6,
        "is_principal": false,
        "soi_weight": 0,
        "rom_weight": 0
      },
      {
        "code": "R50.9",
        "desc": "Fever, unspecified",
        "desc_ar": "حمى، غير محددة",
        "term_en": "fever",
        "matched_text": "fever",
        "confidence": 0.55,
        "is_principal": false,
        "soi_weight": 0,
        "rom_weight": 0
      }
    ],
    "suggested_procedures": [],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.62,
    "phase": "CAC",
    "created_at": "2026-07-15T07:47:17.126Z",
    "source_text": "Patient complains of cough and fever. Suspected pneumonia.",
    "principal_code": "J18.9",
    "secondary_codes": [
      "R05",
      "R50.9"
    ],
    "drg": {
      "code": "194",
      "title_en": "Cardiopulmonary Medical Management",
      "title_ar": "الإدارة الطبية لأمراض القلب والرئة",
      "department_en": "Internal Medicine",
      "department_ar": "الطب الباطني",
      "soi": 2,
      "rom": 2,
      "relative_weight": 0.95,
      "subclass": "194-M-2",
      "methodology": "BrainSAIT-EAPG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Pneumonia, unspecified organism\" (J18.9) anchors DRG family 194 and contributes 1 SOI / 1 ROM point(s).",
          "2 secondary diagnosis(es) (R05, R50.9) add 0 SOI / 0 ROM point(s).",
          "Severity score 1 → SOI tier 2; mortality score 1 → ROM tier 2.",
          "No matching OR procedure detected → Medical partition, relative weight 0.95."
        ],
        "ar": [
          "التشخيص الأساسي \"التهاب رئوي، غير محدد المسبب\" (J18.9) يحدد فئة DRG رقم 194 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "2 تشخيص(ات) ثانوية (R05, R50.9) تضيف 0 نقطة شدة و 0 نقطة خطر وفاة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 1 ← المستوى 2.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 0.95."
        ]
      }
    },
    "detected_language": "en"
  },
  {
    "id": "job8",
    "encounter_id": "e3",
    "suggested_codes": [
      {
        "code": "E11.9",
        "desc": "Type 2 diabetes mellitus without complications",
        "desc_ar": "داء السكري من النوع الثاني بدون مضاعفات",
        "term_en": "diabetes",
        "matched_text": "diabetes",
        "confidence": 0.9,
        "is_principal": true,
        "soi_weight": 1,
        "rom_weight": 1
      }
    ],
    "suggested_procedures": [],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.9,
    "phase": "CAC",
    "created_at": "2026-07-15T06:47:17.127Z",
    "source_text": "Diabetes type 2, E11.9 unspecified, with diabetic nephropathy.",
    "principal_code": "E11.9",
    "secondary_codes": [],
    "drg": {
      "code": "420",
      "title_en": "Diabetes",
      "title_ar": "داء السكري",
      "department_en": "Endocrinology",
      "department_ar": "الغدد الصماء",
      "soi": 2,
      "rom": 2,
      "relative_weight": 0.7,
      "subclass": "420-M-2",
      "methodology": "BrainSAIT-APR-DRG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Type 2 diabetes mellitus without complications\" (E11.9) anchors DRG family 420 and contributes 1 SOI / 1 ROM point(s).",
          "Severity score 1 → SOI tier 2; mortality score 1 → ROM tier 2.",
          "No matching OR procedure detected → Medical partition, relative weight 0.7."
        ],
        "ar": [
          "التشخيص الأساسي \"داء السكري من النوع الثاني بدون مضاعفات\" (E11.9) يحدد فئة DRG رقم 420 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 1 ← المستوى 2.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 0.7."
        ]
      }
    },
    "detected_language": "en"
  },
  {
    "id": "job9",
    "encounter_id": "e4",
    "suggested_codes": [
      {
        "code": "I10",
        "desc": "Essential (primary) hypertension",
        "desc_ar": "ارتفاع ضغط الدم الأساسي (الأولي)",
        "term_en": "high blood pressure",
        "matched_text": "high blood pressure",
        "confidence": 0.99,
        "is_principal": true,
        "soi_weight": 1,
        "rom_weight": 1
      }
    ],
    "suggested_procedures": [],
    "status": "AUTO_DROP",
    "confidence_score": 0.99,
    "phase": "SEMI_AUTONOMOUS",
    "created_at": "2026-07-15T05:47:17.128Z",
    "source_text": "High blood pressure diagnosed, ضغط دم مرتفع controlled with medication.",
    "principal_code": "I10",
    "secondary_codes": [],
    "drg": {
      "code": "201",
      "title_en": "Hypertension",
      "title_ar": "ارتفاع ضغط الدم",
      "department_en": "Cardiology",
      "department_ar": "أمراض القلب",
      "soi": 2,
      "rom": 2,
      "relative_weight": 0.6,
      "subclass": "201-M-2",
      "methodology": "BrainSAIT-EAPG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Essential (primary) hypertension\" (I10) anchors DRG family 201 and contributes 1 SOI / 1 ROM point(s).",
          "Severity score 1 → SOI tier 2; mortality score 1 → ROM tier 2.",
          "No matching OR procedure detected → Medical partition, relative weight 0.6."
        ],
        "ar": [
          "التشخيص الأساسي \"ارتفاع ضغط الدم الأساسي (الأولي)\" (I10) يحدد فئة DRG رقم 201 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 1 ← المستوى 2.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 0.6."
        ]
      }
    },
    "detected_language": "mixed"
  },
  {
    "id": "job10",
    "encounter_id": "e5",
    "suggested_codes": [
      {
        "code": "E11.9",
        "desc": "Type 2 diabetes mellitus without complications",
        "desc_ar": "داء السكري من النوع الثاني بدون مضاعفات",
        "term_ar": "sukari",
        "matched_text": "sukari",
        "confidence": 0.9,
        "is_principal": true,
        "soi_weight": 1,
        "rom_weight": 1
      }
    ],
    "suggested_procedures": [],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.9,
    "phase": "CAC",
    "created_at": "2026-07-15T04:47:17.128Z",
    "source_text": "Patient with sukari symptoms, no complications noted.",
    "principal_code": "E11.9",
    "secondary_codes": [],
    "drg": {
      "code": "420",
      "title_en": "Diabetes",
      "title_ar": "داء السكري",
      "department_en": "Endocrinology",
      "department_ar": "الغدد الصماء",
      "soi": 2,
      "rom": 2,
      "relative_weight": 0.7,
      "subclass": "420-M-2",
      "methodology": "BrainSAIT-EAPG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Type 2 diabetes mellitus without complications\" (E11.9) anchors DRG family 420 and contributes 1 SOI / 1 ROM point(s).",
          "Severity score 1 → SOI tier 2; mortality score 1 → ROM tier 2.",
          "No matching OR procedure detected → Medical partition, relative weight 0.7."
        ],
        "ar": [
          "التشخيص الأساسي \"داء السكري من النوع الثاني بدون مضاعفات\" (E11.9) يحدد فئة DRG رقم 420 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 1 ← المستوى 2.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 0.7."
        ]
      }
    },
    "detected_language": "en"
  },
  {
    "id": "job11",
    "encounter_id": "e1",
    "suggested_codes": [
      {
        "code": "J18.9",
        "desc": "Pneumonia, unspecified organism",
        "desc_ar": "التهاب رئوي، غير محدد المسبب",
        "term_ar": "التهاب رئوي",
        "matched_text": "التهاب رئوي",
        "confidence": 0.85,
        "is_principal": true,
        "soi_weight": 2,
        "rom_weight": 2
      }
    ],
    "suggested_procedures": [],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.85,
    "phase": "CAC",
    "created_at": "2026-07-15T03:47:17.130Z",
    "source_text": "مريض يعاني من التهاب رئوي بكتيري وكسر في الساق اليسرى.",
    "principal_code": "J18.9",
    "secondary_codes": [],
    "drg": {
      "code": "194",
      "title_en": "Cardiopulmonary Medical Management",
      "title_ar": "الإدارة الطبية لأمراض القلب والرئة",
      "department_en": "Internal Medicine",
      "department_ar": "الطب الباطني",
      "soi": 2,
      "rom": 2,
      "relative_weight": 0.95,
      "subclass": "194-M-2",
      "methodology": "BrainSAIT-APR-DRG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Pneumonia, unspecified organism\" (J18.9) anchors DRG family 194 and contributes 1 SOI / 1 ROM point(s).",
          "Age 66 (≥65) adds 1 ROM point.",
          "Severity score 1 → SOI tier 2; mortality score 2 → ROM tier 2.",
          "No matching OR procedure detected → Medical partition, relative weight 0.95."
        ],
        "ar": [
          "التشخيص الأساسي \"التهاب رئوي، غير محدد المسبب\" (J18.9) يحدد فئة DRG رقم 194 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "العمر 66 (≥65) يضيف نقطة خطر وفاة واحدة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 2 ← المستوى 2.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 0.95."
        ]
      }
    },
    "detected_language": "ar"
  },
  {
    "id": "job12",
    "encounter_id": "e2",
    "suggested_codes": [
      {
        "code": "E11.9",
        "desc": "Type 2 diabetes mellitus without complications",
        "desc_ar": "داء السكري من النوع الثاني بدون مضاعفات",
        "term_ar": "السكري",
        "matched_text": "السكري",
        "confidence": 0.9,
        "is_principal": true,
        "soi_weight": 1,
        "rom_weight": 1
      }
    ],
    "suggested_procedures": [],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.9,
    "phase": "CAC",
    "created_at": "2026-07-15T02:47:17.132Z",
    "source_text": "المريض حالة معروفة بداء السكري ويأتي للمراجعة الروتينية دون مضاعفات.",
    "principal_code": "E11.9",
    "secondary_codes": [],
    "drg": {
      "code": "420",
      "title_en": "Diabetes",
      "title_ar": "داء السكري",
      "department_en": "Endocrinology",
      "department_ar": "الغدد الصماء",
      "soi": 2,
      "rom": 2,
      "relative_weight": 0.7,
      "subclass": "420-M-2",
      "methodology": "BrainSAIT-EAPG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Type 2 diabetes mellitus without complications\" (E11.9) anchors DRG family 420 and contributes 1 SOI / 1 ROM point(s).",
          "Severity score 1 → SOI tier 2; mortality score 1 → ROM tier 2.",
          "No matching OR procedure detected → Medical partition, relative weight 0.7."
        ],
        "ar": [
          "التشخيص الأساسي \"داء السكري من النوع الثاني بدون مضاعفات\" (E11.9) يحدد فئة DRG رقم 420 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 1 ← المستوى 2.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 0.7."
        ]
      }
    },
    "detected_language": "ar"
  },
  {
    "id": "job13",
    "encounter_id": "e3",
    "suggested_codes": [
      {
        "code": "K37",
        "desc": "Unspecified appendicitis",
        "desc_ar": "التهاب الزائدة الدودية غير المحدد",
        "term_en": "appendicitis",
        "matched_text": "appendicitis",
        "confidence": 0.75,
        "is_principal": true,
        "soi_weight": 1,
        "rom_weight": 1
      }
    ],
    "suggested_procedures": [],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.75,
    "phase": "CAC",
    "created_at": "2026-07-15T01:47:17.132Z",
    "source_text": "Appendix pain and inflammation, suspected appendicitis.",
    "principal_code": "K37",
    "secondary_codes": [],
    "drg": {
      "code": "261",
      "title_en": "Appendectomy & Appendiceal Conditions",
      "title_ar": "استئصال الزائدة الدودية وحالاتها",
      "department_en": "General Surgery",
      "department_ar": "الجراحة العامة",
      "soi": 2,
      "rom": 2,
      "relative_weight": 0.8,
      "subclass": "261-M-2",
      "methodology": "BrainSAIT-APR-DRG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Unspecified appendicitis\" (K37) anchors DRG family 261 and contributes 1 SOI / 1 ROM point(s).",
          "Severity score 1 → SOI tier 2; mortality score 1 → ROM tier 2.",
          "No matching OR procedure detected → Medical partition, relative weight 0.8."
        ],
        "ar": [
          "التشخيص الأساسي \"التهاب الزائدة الدودية غير المحدد\" (K37) يحدد فئة DRG رقم 261 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 1 ← المستوى 2.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 0.8."
        ]
      }
    },
    "detected_language": "en"
  },
  {
    "id": "job14",
    "encounter_id": "e4",
    "suggested_codes": [
      {
        "code": "I21.9",
        "desc": "Acute myocardial infarction, unspecified",
        "desc_ar": "احتشاء عضلة القلب الحاد، غير محدد",
        "term_en": "myocardial infarction",
        "matched_text": "myocardial infarction",
        "confidence": 0.9,
        "is_principal": true,
        "soi_weight": 3,
        "rom_weight": 3
      }
    ],
    "suggested_procedures": [],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.9,
    "phase": "CAC",
    "created_at": "2026-07-15T00:47:17.133Z",
    "source_text": "Myocardial infarction STEMI confirmed.",
    "principal_code": "I21.9",
    "secondary_codes": [],
    "drg": {
      "code": "190",
      "title_en": "Acute Myocardial Infarction",
      "title_ar": "احتشاء عضلة القلب الحاد",
      "department_en": "Cardiology",
      "department_ar": "أمراض القلب",
      "soi": 2,
      "rom": 3,
      "relative_weight": 1.6,
      "subclass": "190-M-2",
      "methodology": "BrainSAIT-APR-DRG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Acute myocardial infarction, unspecified\" (I21.9) anchors DRG family 190 and contributes 2 SOI / 2 ROM point(s).",
          "Age 68 (≥65) adds 1 ROM point.",
          "Severity score 2 → SOI tier 2; mortality score 3 → ROM tier 3.",
          "No matching OR procedure detected → Medical partition, relative weight 1.6."
        ],
        "ar": [
          "التشخيص الأساسي \"احتشاء عضلة القلب الحاد، غير محدد\" (I21.9) يحدد فئة DRG رقم 190 ويساهم بـ 2 نقطة شدة و 2 نقطة خطر وفاة.",
          "العمر 68 (≥65) يضيف نقطة خطر وفاة واحدة.",
          "درجة الشدة 2 ← المستوى 2؛ درجة خطر الوفاة 3 ← المستوى 3.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 1.6."
        ]
      }
    },
    "detected_language": "en"
  },
  {
    "id": "job15",
    "encounter_id": "e5",
    "suggested_codes": [
      {
        "code": "I10",
        "desc": "Essential (primary) hypertension",
        "desc_ar": "ارتفاع ضغط الدم الأساسي (الأولي)",
        "term_en": "hypertension",
        "matched_text": "hypertension",
        "confidence": 0.99,
        "is_principal": true,
        "soi_weight": 1,
        "rom_weight": 1
      }
    ],
    "suggested_procedures": [],
    "status": "AUTO_DROP",
    "confidence_score": 0.99,
    "phase": "SEMI_AUTONOMOUS",
    "created_at": "2026-07-14T23:47:17.134Z",
    "source_text": "Hypertension crisis, I10 code needed.",
    "principal_code": "I10",
    "secondary_codes": [],
    "drg": {
      "code": "201",
      "title_en": "Hypertension",
      "title_ar": "ارتفاع ضغط الدم",
      "department_en": "Cardiology",
      "department_ar": "أمراض القلب",
      "soi": 2,
      "rom": 2,
      "relative_weight": 0.6,
      "subclass": "201-M-2",
      "methodology": "BrainSAIT-APR-DRG",
      "partition": "Medical",
      "explanation": {
        "en": [
          "Principal diagnosis \"Essential (primary) hypertension\" (I10) anchors DRG family 201 and contributes 1 SOI / 1 ROM point(s).",
          "Severity score 1 → SOI tier 2; mortality score 1 → ROM tier 2.",
          "No matching OR procedure detected → Medical partition, relative weight 0.6."
        ],
        "ar": [
          "التشخيص الأساسي \"ارتفاع ضغط الدم الأساسي (الأولي)\" (I10) يحدد فئة DRG رقم 201 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 1 ← المستوى 2.",
          "لم يتم رصد إجراء جراحي مطابق ← القسم الطبي، الوزن النسبي 0.6."
        ]
      }
    },
    "detected_language": "en"
  },
  {
    "id": "job16",
    "encounter_id": "e1",
    "suggested_codes": [
      {
        "code": "K37",
        "desc": "Unspecified appendicitis",
        "desc_ar": "التهاب الزائدة الدودية غير المحدد",
        "term_en": "appendicitis",
        "matched_text": "appendicitis",
        "confidence": 0.9,
        "is_principal": true,
        "soi_weight": 1,
        "rom_weight": 1
      }
    ],
    "suggested_procedures": [
      {
        "code": "PR-APPY",
        "desc": "Appendectomy",
        "desc_ar": "استئصال الزائدة الدودية",
        "matched_text": "appendectomy"
      }
    ],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.9,
    "phase": "CAC",
    "created_at": "2026-07-14T22:47:17.136Z",
    "source_text": "Patient underwent appendectomy for acute appendicitis with perforation.",
    "principal_code": "K37",
    "secondary_codes": [],
    "drg": {
      "code": "261",
      "title_en": "Appendectomy & Appendiceal Conditions",
      "title_ar": "استئصال الزائدة الدودية وحالاتها",
      "department_en": "General Surgery",
      "department_ar": "الجراحة العامة",
      "soi": 2,
      "rom": 2,
      "relative_weight": 1.28,
      "subclass": "261-S-2",
      "methodology": "BrainSAIT-APR-DRG",
      "partition": "Surgical",
      "procedure": {
        "code": "PR-APPY",
        "desc_en": "Appendectomy",
        "desc_ar": "استئصال الزائدة الدودية"
      },
      "explanation": {
        "en": [
          "Principal diagnosis \"Unspecified appendicitis\" (K37) anchors DRG family 261 and contributes 1 SOI / 1 ROM point(s).",
          "Severity score 1 → SOI tier 2; mortality score 1 → ROM tier 2.",
          "Procedure \"Appendectomy\" detected → Surgical partition, relative weight ×1.6 (0.8 → 1.28)."
        ],
        "ar": [
          "التشخيص الأساسي \"التهاب الزائدة الدودية غير المحدد\" (K37) يحدد فئة DRG رقم 261 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 1 ← المستوى 2.",
          "تم رصد إجراء \"استئصال الزائدة الدودية\" ← القسم الجراحي، الوزن النسبي ×1.6 (0.8 ← 1.28)."
        ]
      }
    },
    "detected_language": "en"
  },
  {
    "id": "job17",
    "encounter_id": "e2",
    "suggested_codes": [
      {
        "code": "K81.9",
        "desc": "Cholecystitis, unspecified",
        "desc_ar": "التهاب المرارة، غير محدد",
        "term_ar": "التهاب المرارة",
        "matched_text": "التهاب المرارة",
        "confidence": 0.86,
        "is_principal": true,
        "soi_weight": 2,
        "rom_weight": 1
      }
    ],
    "suggested_procedures": [
      {
        "code": "PR-CHOLE",
        "desc": "Cholecystectomy",
        "desc_ar": "استئصال المرارة",
        "matched_text": "استئصال المرارة"
      }
    ],
    "status": "NEEDS_REVIEW",
    "confidence_score": 0.86,
    "phase": "CAC",
    "created_at": "2026-07-14T21:47:17.137Z",
    "source_text": "مريض تم له استئصال المرارة بسبب التهاب المرارة الحاد.",
    "principal_code": "K81.9",
    "secondary_codes": [],
    "drg": {
      "code": "220",
      "title_en": "Cholecystitis & Biliary Disease",
      "title_ar": "التهاب المرارة وأمراض القنوات الصفراوية",
      "department_en": "General Surgery",
      "department_ar": "الجراحة العامة",
      "soi": 2,
      "rom": 2,
      "relative_weight": 1.2,
      "subclass": "220-S-2",
      "methodology": "BrainSAIT-APR-DRG",
      "partition": "Surgical",
      "procedure": {
        "code": "PR-CHOLE",
        "desc_en": "Cholecystectomy",
        "desc_ar": "استئصال المرارة"
      },
      "explanation": {
        "en": [
          "Principal diagnosis \"Cholecystitis, unspecified\" (K81.9) anchors DRG family 220 and contributes 1 SOI / 1 ROM point(s).",
          "Severity score 1 → SOI tier 2; mortality score 1 → ROM tier 2.",
          "Procedure \"Cholecystectomy\" detected → Surgical partition, relative weight ×1.5 (0.8 → 1.2)."
        ],
        "ar": [
          "التشخيص الأساسي \"التهاب المرارة، غير محدد\" (K81.9) يحدد فئة DRG رقم 220 ويساهم بـ 1 نقطة شدة و 1 نقطة خطر وفاة.",
          "درجة الشدة 1 ← المستوى 2؛ درجة خطر الوفاة 1 ← المستوى 2.",
          "تم رصد إجراء \"استئصال المرارة\" ← القسم الجراحي، الوزن النسبي ×1.5 (0.8 ← 1.2)."
        ]
      }
    },
    "detected_language": "ar"
  }
];
export const MOCK_NUDGES: Nudge[] = [
  {
    "id": "I21.9_mi_type_e2",
    "encounter_id": "e2",
    "severity": "critical",
    "prompt": "Specify the type of myocardial infarction (STEMI vs. NSTEMI) for a higher-specificity code.",
    "prompt_ar": "يرجى تحديد نوع احتشاء عضلة القلب (مع ارتفاع ST أو بدونه) لترميز أعلى دقة.",
    "soi_impact": "Closing this documentation gap could raise SOI from 2 to 3.",
    "soi_impact_ar": "قد يؤدي إغلاق هذه الفجوة التوثيقية إلى رفع درجة شدة المرض (SOI) من 2 إلى 3.",
    "status": "resolved",
    "created_at": "2026-07-15T13:47:17.196Z"
  },
  {
    "id": "J18.9_pneumonia_organism_e2",
    "encounter_id": "e2",
    "severity": "warning",
    "prompt": "Specify the causative organism for 'pneumonia' (e.g., bacterial, viral, aspiration) to support a more specific code.",
    "prompt_ar": "يرجى تحديد العامل المسبب لـ\"الالتهاب الرئوي\" (مثل بكتيري أو فيروسي أو استنشاقي) لدعم ترميز أكثر دقة.",
    "soi_impact": "Closing this documentation gap could raise SOI from 2 to 3.",
    "soi_impact_ar": "قد يؤدي إغلاق هذه الفجوة التوثيقية إلى رفع درجة شدة المرض (SOI) من 2 إلى 3.",
    "status": "active",
    "created_at": "2026-07-15T12:17:17.196Z"
  },
  {
    "id": "I10_htn_crisis_e4",
    "encounter_id": "e4",
    "severity": "info",
    "prompt": "Clarify whether this represents a hypertensive crisis/emergency for a higher-acuity code.",
    "prompt_ar": "يرجى توضيح ما إذا كانت الحالة أزمة ارتفاع ضغط دم طارئة لترميز أعلى حدة.",
    "soi_impact": "Closing this documentation gap could raise SOI from 2 to 3.",
    "soi_impact_ar": "قد يؤدي إغلاق هذه الفجوة التوثيقية إلى رفع درجة شدة المرض (SOI) من 2 إلى 3.",
    "status": "active",
    "created_at": "2026-07-15T10:47:17.196Z"
  },
  {
    "id": "E11.9_diabetes_complication_e5",
    "encounter_id": "e5",
    "severity": "warning",
    "prompt": "Document any diabetic complication (neuropathy, nephropathy, retinopathy, ketoacidosis) if present — this materially changes SOI.",
    "prompt_ar": "يرجى توثيق أي مضاعفات لداء السكري (اعتلال الأعصاب/الكلى/الشبكية أو الحماض الكيتوني) إن وُجدت — يؤثر ذلك بشكل جوهري على درجة شدة المرض.",
    "soi_impact": "Closing this documentation gap could raise SOI from 2 to 4.",
    "soi_impact_ar": "قد يؤدي إغلاق هذه الفجوة التوثيقية إلى رفع درجة شدة المرض (SOI) من 2 إلى 4.",
    "status": "active",
    "created_at": "2026-07-15T09:17:17.196Z"
  },
  {
    "id": "E11.9_diabetes_complication_e2",
    "encounter_id": "e2",
    "severity": "warning",
    "prompt": "Document any diabetic complication (neuropathy, nephropathy, retinopathy, ketoacidosis) if present — this materially changes SOI.",
    "prompt_ar": "يرجى توثيق أي مضاعفات لداء السكري (اعتلال الأعصاب/الكلى/الشبكية أو الحماض الكيتوني) إن وُجدت — يؤثر ذلك بشكل جوهري على درجة شدة المرض.",
    "soi_impact": "Closing this documentation gap could raise SOI from 2 to 4.",
    "soi_impact_ar": "قد يؤدي إغلاق هذه الفجوة التوثيقية إلى رفع درجة شدة المرض (SOI) من 2 إلى 4.",
    "status": "active",
    "created_at": "2026-07-15T07:47:17.196Z"
  },
  {
    "id": "K37_appendicitis_perforation_e3",
    "encounter_id": "e3",
    "severity": "warning",
    "prompt": "Clarify if the appendicitis is with or without perforation/peritonitis.",
    "prompt_ar": "يرجى توضيح ما إذا كان التهاب الزائدة مصحوبًا بانثقاب أو التهاب الصفاق أم لا.",
    "soi_impact": "Closing this documentation gap could raise SOI from 2 to 3.",
    "soi_impact_ar": "قد يؤدي إغلاق هذه الفجوة التوثيقية إلى رفع درجة شدة المرض (SOI) من 2 إلى 3.",
    "status": "resolved",
    "created_at": "2026-07-15T06:17:17.196Z"
  }
];
export const MOCK_ANALYTICS: Analytics[] = [
  {
    "id": "a1",
    "job_id": "job1",
    "accuracy": 65,
    "phase": "CAC",
    "relative_weight": 0.95,
    "soi": 2,
    "rom": 2,
    "drg_family": "194",
    "department_en": "Internal Medicine",
    "department_ar": "الطب الباطني",
    "created_at": "2026-07-15T13:47:17.109Z"
  },
  {
    "id": "a2",
    "job_id": "job2",
    "accuracy": 90,
    "phase": "CAC",
    "relative_weight": 1.6,
    "soi": 2,
    "rom": 2,
    "drg_family": "190",
    "department_en": "Cardiology",
    "department_ar": "أمراض القلب",
    "created_at": "2026-07-15T12:47:17.117Z"
  },
  {
    "id": "a3",
    "job_id": "job3",
    "accuracy": 90,
    "phase": "CAC",
    "relative_weight": 0.8,
    "soi": 2,
    "rom": 2,
    "drg_family": "261",
    "department_en": "General Surgery",
    "department_ar": "الجراحة العامة",
    "created_at": "2026-07-15T11:47:17.119Z"
  },
  {
    "id": "a4",
    "job_id": "job4",
    "accuracy": 88,
    "phase": "CAC",
    "relative_weight": 0.75,
    "soi": 2,
    "rom": 1,
    "drg_family": "302",
    "department_en": "Orthopedics",
    "department_ar": "جراحة العظام",
    "created_at": "2026-07-15T10:47:17.123Z"
  },
  {
    "id": "a5",
    "job_id": "job5",
    "accuracy": 80,
    "phase": "CAC",
    "relative_weight": 0.65,
    "soi": 2,
    "rom": 2,
    "drg_family": "466",
    "department_en": "Urology",
    "department_ar": "المسالك البولية",
    "created_at": "2026-07-15T09:47:17.123Z"
  },
  {
    "id": "a6",
    "job_id": "job6",
    "accuracy": 99,
    "phase": "AUTONOMOUS",
    "relative_weight": 0.6,
    "soi": 2,
    "rom": 2,
    "drg_family": "201",
    "department_en": "Cardiology",
    "department_ar": "أمراض القلب",
    "created_at": "2026-07-15T08:47:17.124Z"
  },
  {
    "id": "a7",
    "job_id": "job7",
    "accuracy": 62,
    "phase": "CAC",
    "relative_weight": 0.95,
    "soi": 2,
    "rom": 2,
    "drg_family": "194",
    "department_en": "Internal Medicine",
    "department_ar": "الطب الباطني",
    "created_at": "2026-07-15T07:47:17.126Z"
  },
  {
    "id": "a8",
    "job_id": "job8",
    "accuracy": 90,
    "phase": "CAC",
    "relative_weight": 0.7,
    "soi": 2,
    "rom": 2,
    "drg_family": "420",
    "department_en": "Endocrinology",
    "department_ar": "الغدد الصماء",
    "created_at": "2026-07-15T06:47:17.127Z"
  },
  {
    "id": "a9",
    "job_id": "job9",
    "accuracy": 99,
    "phase": "SEMI_AUTONOMOUS",
    "relative_weight": 0.6,
    "soi": 2,
    "rom": 2,
    "drg_family": "201",
    "department_en": "Cardiology",
    "department_ar": "أمراض القلب",
    "created_at": "2026-07-15T05:47:17.128Z"
  },
  {
    "id": "a10",
    "job_id": "job10",
    "accuracy": 90,
    "phase": "CAC",
    "relative_weight": 0.7,
    "soi": 2,
    "rom": 2,
    "drg_family": "420",
    "department_en": "Endocrinology",
    "department_ar": "الغدد الصماء",
    "created_at": "2026-07-15T04:47:17.128Z"
  },
  {
    "id": "a11",
    "job_id": "job11",
    "accuracy": 85,
    "phase": "CAC",
    "relative_weight": 0.95,
    "soi": 2,
    "rom": 2,
    "drg_family": "194",
    "department_en": "Internal Medicine",
    "department_ar": "الطب الباطني",
    "created_at": "2026-07-15T03:47:17.130Z"
  },
  {
    "id": "a12",
    "job_id": "job12",
    "accuracy": 90,
    "phase": "CAC",
    "relative_weight": 0.7,
    "soi": 2,
    "rom": 2,
    "drg_family": "420",
    "department_en": "Endocrinology",
    "department_ar": "الغدد الصماء",
    "created_at": "2026-07-15T02:47:17.132Z"
  },
  {
    "id": "a13",
    "job_id": "job13",
    "accuracy": 75,
    "phase": "CAC",
    "relative_weight": 0.8,
    "soi": 2,
    "rom": 2,
    "drg_family": "261",
    "department_en": "General Surgery",
    "department_ar": "الجراحة العامة",
    "created_at": "2026-07-15T01:47:17.132Z"
  },
  {
    "id": "a14",
    "job_id": "job14",
    "accuracy": 90,
    "phase": "CAC",
    "relative_weight": 1.6,
    "soi": 2,
    "rom": 3,
    "drg_family": "190",
    "department_en": "Cardiology",
    "department_ar": "أمراض القلب",
    "created_at": "2026-07-15T00:47:17.133Z"
  },
  {
    "id": "a15",
    "job_id": "job15",
    "accuracy": 99,
    "phase": "SEMI_AUTONOMOUS",
    "relative_weight": 0.6,
    "soi": 2,
    "rom": 2,
    "drg_family": "201",
    "department_en": "Cardiology",
    "department_ar": "أمراض القلب",
    "created_at": "2026-07-14T23:47:17.134Z"
  },
  {
    "id": "a16",
    "job_id": "job16",
    "accuracy": 90,
    "phase": "CAC",
    "relative_weight": 1.28,
    "soi": 2,
    "rom": 2,
    "drg_family": "261",
    "department_en": "General Surgery",
    "department_ar": "الجراحة العامة",
    "created_at": "2026-07-14T22:47:17.136Z"
  },
  {
    "id": "a17",
    "job_id": "job17",
    "accuracy": 86,
    "phase": "CAC",
    "relative_weight": 1.2,
    "soi": 2,
    "rom": 2,
    "drg_family": "220",
    "department_en": "General Surgery",
    "department_ar": "الجراحة العامة",
    "created_at": "2026-07-14T21:47:17.137Z"
  }
];
// Demo accounts — rotate/remove before real deployment. See README "Default credentials".
export const MOCK_ACCOUNTS: Account[] = [
  {
    "id": "admin",
    "username": "admin",
    "password_hash": "pBLrx76H3ZQoY8Q-IfWWqf0hrkvt2hxumlQ_5YssDa4",
    "salt": "cU7RL5GhmkIEBVTZYfOXcg",
    "role": "admin"
  },
  {
    "id": "coder",
    "username": "coder",
    "password_hash": "ivBv_KGWvB5ZqcB0hW40gUVGne02D3rkj1cRwhjjsr0",
    "salt": "VjK-MGxFG9-uMC1OyRzaSQ",
    "role": "coder"
  }
];
