/**
 * Generates shared/seed-data.generated.ts by running the real bilingual
 * coding engine over NOTE_PLAN once, at build time, in Node/Bun.
 *
 * Why this exists: the Worker used to compute this seed data live (at
 * module scope, then later lazily on first request) so demo data could
 * never drift from real engine behavior. Both approaches ran ~85 lexicon
 * entries x 17 notes of regex matching inside the Workers isolate, which
 * exceeded Cloudflare's startup CPU budget (module scope) and its
 * per-request CPU budget (lazy). Baking the output into a static generated
 * module keeps the "never drifts from the engine" guarantee while making
 * the runtime cost of loading it zero.
 *
 * Run `bun run generate:seed` after changing NOTE_PLAN, the lexicon, or the
 * grouper/engine logic, and commit the regenerated file.
 */
import { runCodingEngine, classifyAutomationPhase } from '../shared/coding-engine';
import { generateCdiNudges } from '../shared/cdi-rules';
import { NOTE_PLAN } from '../shared/mock-data';
import type { CodingJob, Nudge, Analytics } from '../shared/types';

const codingJobs: CodingJob[] = NOTE_PLAN.map((plan, index) => {
  const engineResult = runCodingEngine(plan.note, { age: plan.age, encounterType: plan.encounter_type });
  const { phase, status } = classifyAutomationPhase(engineResult.confidence_score, plan.visit_complexity ?? 'standard');
  return {
    id: `job${index + 1}`,
    encounter_id: plan.encounter_id,
    suggested_codes: engineResult.suggested_codes,
    suggested_procedures: engineResult.suggested_procedures,
    status,
    confidence_score: engineResult.confidence_score,
    phase,
    created_at: new Date(Date.now() - index * 3_600_000).toISOString(),
    source_text: plan.note,
    principal_code: engineResult.principal_code,
    secondary_codes: engineResult.secondary_codes,
    drg: engineResult.drg,
    detected_language: engineResult.detected_language,
  };
});

const nudges: Nudge[] = NOTE_PLAN.flatMap((plan) =>
  generateCdiNudges(plan.note, plan.encounter_id, { age: plan.age, encounterType: plan.encounter_type })
).map((nudge, index) => ({
  ...nudge,
  status: index % 5 === 0 ? 'resolved' : index % 7 === 0 ? 'dismissed' : 'active',
  created_at: new Date(Date.now() - index * 5_400_000).toISOString(),
}));

const analytics: Analytics[] = codingJobs.map((job, index) => ({
  id: `a${index + 1}`,
  job_id: job.id,
  accuracy: Math.round(job.confidence_score * 100),
  phase: job.phase,
  relative_weight: job.drg?.relative_weight,
  soi: job.drg?.soi,
  rom: job.drg?.rom,
  created_at: job.created_at,
}));

const header = `/**
 * AUTO-GENERATED by scripts/generate-seed-data.ts. Do not edit by hand.
 * Regenerate with \`bun run generate:seed\` after changing NOTE_PLAN, the
 * bilingual lexicon, or the coding/DRG engine.
 */
import type { CodingJob, Nudge, Analytics } from './types';
`;

const body = [
  `export const MOCK_CODING_JOBS: CodingJob[] = ${JSON.stringify(codingJobs, null, 2)};`,
  `export const MOCK_NUDGES: Nudge[] = ${JSON.stringify(nudges, null, 2)};`,
  `export const MOCK_ANALYTICS: Analytics[] = ${JSON.stringify(analytics, null, 2)};`,
].join('\n');

await Bun.write(new URL('../shared/seed-data.generated.ts', import.meta.url), `${header}\n${body}\n`);
console.log(`Generated shared/seed-data.generated.ts: ${codingJobs.length} coding jobs, ${nudges.length} nudges, ${analytics.length} analytics rows.`);
